// ─────────────────────────────────────────────────────────────────────────────
// RSU ACADEMY — Banco de preguntas de quiz por módulo
// Cada módulo tiene 6-8 preguntas de opción múltiple basadas en el contenido
// real de sus lecciones. Formato de cada pregunta:
//   { q: 'texto', options: ['a','b','c','d'], correct: index, explanation: 'texto' }
// El quiz se muestra al final del módulo (tras todas sus lecciones).
// ─────────────────────────────────────────────────────────────────────────────

export const QUIZZES = {

    0: {
        title: 'Quiz — RSU Terminal',
        questions: [
            { q: '¿Qué es RSU Terminal según su propia filosofía?', options: ['Un robot de trading con señales automáticas de compra/venta', 'Una herramienta de análisis — las decisiones las toma el usuario', 'Un broker regulado', 'Un servicio de gestión de carteras de terceros'], correct: 1, explanation: 'RSU Terminal no genera señales automáticas ni gestiona el dinero del usuario — es una herramienta de análisis. La responsabilidad de la decisión es siempre del trader.' },
            { q: '¿Cómo se financia la infraestructura de RSU Terminal?', options: ['Con publicidad de brokers', 'Con las contribuciones de una comunidad de unos 100 traders', 'Con comisiones por cada operación ejecutada', 'Con la venta de datos de usuarios'], correct: 1, explanation: 'La terminal la mantiene una comunidad de ~100 traders que cubren los costes de infraestructura y APIs — sin anunciantes ni conflictos de interés.' },
            { q: '¿Cuál de estas NO es uno de los 3 pilares de la metodología RSU?', options: ['Contexto de mercado favorable', 'Activo de calidad (líder, RS alto)', 'Setup con ratio riesgo/recompensa favorable', 'Un indicador técnico único e infalible'], correct: 3, explanation: 'La metodología se basa en tres pilares: contexto, calidad del activo y R:R favorable. No existe ningún indicador único infalible.' },
            { q: 'Según la comparativa "trader amateur vs trader RSU", ¿qué se define primero antes de abrir una posición?', options: ['Cuánto se puede ganar', 'El stop loss, antes de entrar', 'El tamaño según intuición', 'Nada, se decide sobre la marcha'], correct: 1, explanation: 'El trader RSU define el stop antes de entrar; el amateur entra primero y piensa el stop después.' },
            { q: '¿Cuál es el ratio riesgo/recompensa mínimo que exige la metodología RSU para operar un setup?', options: ['1:1', '1:1.5', '1:2', 'No hay mínimo, depende del setup'], correct: 2, explanation: 'Sin al menos 1:2 de R:R, la metodología RSU no considera el setup operable, aunque el contexto y el activo sean buenos.' },
            { q: '¿Qué herramienta combina el scanner de estilo IBD con el Trend Template sobre el S&P 500 completo?', options: ['Market Dashboard', 'CAN SLIM Scanner', 'Options Flow', 'RS/RW Scanner'], correct: 1, explanation: 'El scanner CAN SLIM aplica el Trend Template y criterios IBD sobre todo el S&P 500 para identificar candidatos.' },
            { q: 'En el estado de mercado "Uptrend Under Pressure" del flujo de trabajo semanal, ¿cuál es la postura recomendada?', options: ['Ofensiva — abrir posiciones a tamaño completo', 'Defensiva — no abrir nuevas, proteger las existentes', 'Preservar capital totalmente', 'Ignorar el estado de mercado'], correct: 1, explanation: 'Uptrend Under Pressure pide postura defensiva: no se abren posiciones nuevas y se protegen las existentes hasta que el mercado aclare.' },
        ]
    },

    1: {
        title: 'Quiz — Configuración de Gráficos',
        questions: [
            { q: '¿A qué media diaria equivale aproximadamente la MA10 mensual?', options: ['SMA 50 diaria', 'SMA 100 diaria', 'SMA 200 diaria', 'SMA 20 diaria'], correct: 2, explanation: 'La media de 10 meses filtra el ruido igual que la SMA 200 diaria, pero usando cierres mensuales.' },
            { q: 'Según la regla de alineación Mensual-Semanal, ¿cuándo se maximiza la probabilidad de un long?', options: ['Cuando el mensual es alcista, sin mirar el semanal', 'Cuando semanal y mensual coinciden en la misma dirección', 'Cuando el diario da una señal aislada', 'Cuando el semanal contradice al mensual'], correct: 1, explanation: 'La regla de oro es operar solo cuando el semanal coincide con el mensual.' },
            { q: '¿A qué media diaria equivale aproximadamente la EMA 21 semanal?', options: ['~EMA 21 diaria', '~EMA 50 diaria', '~EMA 100 diaria', '~EMA 200 diaria'], correct: 2, explanation: 'La EMA 21 semanal actúa de forma similar a la EMA 100 diaria — un soporte dinámico de medio plazo.' },
            { q: '¿Cuál es la configuración de medias recomendada en el "gráfico profesional" limpio?', options: ['Solo SMA 200', 'EMA 21 + SMA 50 + SMA 200, nada más', '5 medias distintas para cruzar señales', 'RSI + MACD + Bollinger + EMA 21'], correct: 1, explanation: 'La configuración mínima recomendada es EMA 21 (naranja), SMA 50 (azul) y SMA 200 (rojo) — sin indicadores adicionales en el panel principal.' },
            { q: '¿Qué diferencia fundamental hay entre una EMA y una SMA del mismo periodo?', options: ['La EMA usa datos semanales y la SMA diarios', 'La EMA pondera más el precio reciente, por eso reacciona antes', 'No hay ninguna diferencia real', 'La SMA solo se puede usar en cripto'], correct: 1, explanation: 'La EMA pondera de forma decreciente hacia atrás, dando más peso al precio reciente — por eso reacciona antes que la SMA.' },
            { q: '¿Por qué se usa el periodo 21 para la EMA y no otro número cualquiera?', options: ['Es un número aleatorio sin importancia', 'Corresponde aproximadamente a un mes de sesiones bursátiles', 'Es el periodo mínimo que permite TradingView', 'Porque coincide con el RSI'], correct: 1, explanation: '21 sesiones equivalen aproximadamente a un mes de trading — corto para reaccionar, largo para no ser ruido de 2-3 días.' },
            { q: 'Para decidir una salida usando la EMA, ¿qué es lo único que realmente cuenta?', options: ['Que la mecha toque la EMA', 'El volumen del día, sin mirar el precio', 'El cierre de la vela respecto a la EMA', 'La opinión de otros traders en redes'], correct: 2, explanation: 'Una mecha que toca la EMA sin que el cierre quede por debajo es un test normal. Solo el primer cierre por debajo es señal de salida.' },
            { q: 'En un Golden Cross clásico, ¿qué ocurre exactamente?', options: ['La EMA 21 cruza sobre la SMA 50', 'La SMA 50 cruza al alza por encima de la SMA 200', 'El precio cruza sobre la SMA 200', 'El RSI cruza sobre 70'], correct: 1, explanation: 'El Golden Cross es el cruce alcista de la SMA 50 sobre la SMA 200 — una señal tardía de confirmación de régimen, no de timing de entrada.' },
        ]
    },

    2: {
        title: 'Quiz — Estructura de Mercado',
        questions: [
            { q: '¿Cuántos HH consecutivos, como mínimo, se necesitan para hablar de tendencia alcista establecida?', options: ['Con uno es suficiente', 'Al menos dos, cada uno precedido de un retroceso', 'Cinco o más', 'No hace falta ningún HH, basta con el volumen'], correct: 1, explanation: 'Un solo máximo más alto no confirma tendencia — se necesitan al menos dos HH consecutivos, cada uno con un retroceso previo claro.' },
            { q: '¿Qué representa un Higher Low (HL) en términos de comportamiento institucional?', options: ['Un error de lectura del gráfico', 'La huella de acumulación de un comprador institucional', 'Una señal de venta inminente', 'Un patrón sin significado real'], correct: 1, explanation: 'Las instituciones compran en correcciones para no mover el precio de golpe — el resultado son mínimos cada vez más altos.' },
            { q: '¿Cuál es la entrada de menor riesgo en una tendencia bajista, según la lección de Máximos Decrecientes?', options: ['Vender en la zona del LH anticipando el giro, sin confirmación', 'Vender en la ruptura del último mínimo y en el retest del nivel roto', 'Vender en cualquier rebote inmediatamente', 'Comprar cada rebote pensando que ya cayó suficiente'], correct: 1, explanation: 'La entrada de menor riesgo espera la ruptura del último mínimo relevante y el retest del nivel (ahora resistencia).' },
            { q: '¿Cuál es la secuencia correcta para confirmar un cambio de tendencia de alcista a bajista?', options: ['Primero rompe el HH, luego falla el HL', 'Primero falla el HL, luego se rompe, luego no se supera el último HH', 'Solo hace falta un cierre bajista', 'El volumen decide el cambio de tendencia por sí solo'], correct: 1, explanation: 'El orden típico es: falla el HL, se rompe a la baja, y finalmente el precio no logra superar el último HH.' },
            { q: 'Con estructura "HH sin HL" (máximos crecientes pero sin mínimos crecientes claros), ¿qué interpretación es correcta?', options: ['Tendencia alcista sana, comprar sin dudar', 'Tendencia frágil con retrocesos profundos — precaución', 'Tendencia bajista confirmada', 'Debe ignorarse, no aporta información'], correct: 1, explanation: 'HH sin HL indica una tendencia frágil, con retrocesos más profundos de lo saludable.' },
            { q: '¿Qué margen recomienda la lección para el stop bajo un HL, en vez de ponerlo justo en el nivel?', options: ['Ningún margen, justo en el HL', '0.5-1% por debajo del HL', '10% por debajo del HL', 'El doble del tamaño de la vela'], correct: 1, explanation: 'El precio suele hacer un spike bajo el HL antes de recuperar — un margen de 0.5-1% evita ser sacado por ese ruido.' },
            { q: 'Con "HH + LL mezclados" en la matriz final de la lección 2-4, ¿cuál es la conclusión inmediata?', options: ['Tendencia alcista clara', 'Tendencia bajista clara', 'Lateral o transición — esperar claridad', 'Señal de comprar agresivamente'], correct: 2, explanation: 'Máximos y mínimos mezclados sin secuencia clara señalan una fase lateral o de transición.' },
        ]
    },

    3: {
        title: 'Quiz — Análisis de Tendencia',
        questions: [
            { q: 'Según el modelo de tres fases de la tendencia alcista, ¿en qué fase se gana la mayoría del dinero?', options: ['Fase de Acumulación', 'Fase de Tendencia', 'Fase de Distribución', 'En todas por igual'], correct: 1, explanation: 'La Fase de Tendencia es donde se establecen HH y HL claramente y es la más fácil de operar.' },
            { q: '¿Cuál es la zona de entrada de menor riesgo según la tabla de zonas de entrada en tendencia alcista?', options: ['Ruptura de consolidación', 'Retroceso a SMA 50', 'Retroceso a EMA 21', 'Retroceso a soporte previo'], correct: 2, explanation: 'El retroceso a EMA 21 en tendencia fuerte es la zona con menor riesgo y mayor probabilidad, según la tabla.' },
            { q: '¿Cuál es la señal más temprana y fiable de que una tendencia alcista puede estar cambiando a bajista?', options: ['El primer LL confirmado', 'El primer LH confirmado tras la tendencia alcista', 'Una sola vela bajista grande', 'El RSI supera 70'], correct: 1, explanation: 'El primer LH confirmado es la señal más temprana de posible cambio de control.' },
            { q: 'En tendencia bajista, ¿cuándo deja un rebote de ser una trampa y se convierte en señal de compra?', options: ['En cuanto el precio sube dos días seguidos', 'Cuando supera el último LH relevante con cierre semanal', 'Nunca, todos los rebotes en bajista son trampa', 'Cuando el volumen baja'], correct: 1, explanation: 'Un rebote no es señal de compra hasta que supera el último LH relevante con un cierre semanal.' },
            { q: 'Según la lección de rango lateral, ¿qué amplitud mínima debería tener un rango para operarlo con sentido?', options: ['Cualquier amplitud sirve', 'Al menos 8-10% entre soporte y resistencia', 'Al menos 50%', 'No importa la amplitud, solo el volumen'], correct: 1, explanation: 'Rangos muy estrechos (menos del 5%) no ofrecen recorrido suficiente para un ratio riesgo/recompensa positivo.' },
            { q: '¿Cuántos toques necesita una línea de tendencia para considerarse validada, según la "regla de los tres puntos"?', options: ['Un solo toque', 'Dos toques', 'Tres toques, con rebote confirmado en el tercero', 'No hace falta ningún toque'], correct: 2, explanation: 'Con solo dos puntos cualquier línea puede dibujarse. El tercer toque con rebote valida la línea.' },
            { q: '¿Qué le ocurre a una línea de tendencia alcista una vez que se rompe a la baja?', options: ['Desaparece, ya no tiene ningún valor', 'Pasa a actuar como resistencia en el rebote posterior (polaridad)', 'Se convierte automáticamente en soporte más fuerte', 'Solo es relevante en el gráfico mensual'], correct: 1, explanation: 'El fenómeno de polaridad también aplica a líneas de tendencia: una línea alcista rota pasa a actuar como resistencia.' },
        ]
    },

    4: {
        title: 'Quiz — Soporte y Resistencia',
        questions: [
            { q: '¿Qué mide la "calidad" de un soporte fresco según la lección?', options: ['El número de indicadores que lo señalan', 'La fuerza del rebote original desde ese nivel', 'El color con el que está marcado', 'La hora del día en que se formó'], correct: 1, explanation: 'Un rebote del 15% desde el soporte es mucho más significativo que uno del 3% — mide convicción compradora.' },
            { q: 'Tras el primer retest de un soporte fresco, ¿qué pasa con su clasificación?', options: ['Sigue siendo fresco indefinidamente', 'Pasa a ser soporte testeado — válido pero con menos fuerza', 'Deja de ser un nivel relevante inmediatamente', 'Se convierte automáticamente en resistencia'], correct: 1, explanation: 'Un soporte fresco solo lo es una vez. Tras el primer retest pasa a soporte testeado.' },
            { q: '¿Qué tipo de resistencia tiene la mayor fiabilidad según la tabla de tipos de resistencia?', options: ['Resistencia intradiaria', 'Techo del rango lateral actual', 'Máximo histórico (ATH), nunca superado antes', 'Resistencia de tendencia bajista reciente'], correct: 2, explanation: 'El máximo histórico (ATH) es la resistencia de mayor fiabilidad porque nunca ha sido superada.' },
            { q: '¿Qué es el "overhead supply" según el concepto de la lección de Resistencia Mayor?', options: ['El volumen medio de las últimas 20 sesiones', 'La presión vendedora acumulada de traders en pérdidas por encima del precio actual', 'Un tipo de vela japonesa', 'Un indicador de sentimiento de opciones'], correct: 1, explanation: 'Overhead supply es la presión vendedora acumulada de quienes compraron por encima del precio actual y están en pérdidas.' },
            { q: 'Según la técnica de marcado de zonas, si el gráfico tiene más de 6-7 zonas marcadas, ¿qué se recomienda?', options: ['Añadir aún más zonas para mayor precisión', 'Es excesivo — quedarse solo con las zonas que generan una acción clara', 'No importa la cantidad de zonas', 'Cambiar de timeframe'], correct: 1, explanation: 'Cada zona adicional reduce la claridad y aumenta la parálisis.' },
            { q: 'Con volumen alto y creciente en cada toque sucesivo de un soporte, ¿qué acción se recomienda?', options: ['El soporte aguantará — comprar con confianza', 'El soporte está agotado, evitar', 'Es una señal irrelevante', 'Vender en corto inmediatamente'], correct: 0, explanation: 'Volumen alto y creciente en cada toque indica compradores activos y comprometidos.' },
            { q: '¿Qué patrón describe un "stop hunt" antes de la ruptura definitiva de un nivel muy testeado?', options: ['El precio nunca se acerca al nivel antes de romperlo', 'Un spike breve por debajo del soporte, recuperación momentánea, y ruptura definitiva después', 'Un cruce de medias móviles', 'Un gap alcista sin razón aparente'], correct: 1, explanation: 'Es un patrón común: el precio perfora brevemente el nivel, rebota un momento, y luego rompe de forma definitiva.' },
        ]
    },

    5: {
        title: 'Quiz — Oferta y Demanda',
        questions: [
            { q: '¿Cuál es el patrón de zona de demanda con mayor fuerza según la tabla?', options: ['Rally-Base-Rally (RBR)', 'Drop-Base-Rally (DBR)', 'Rally-Base directo', 'Ninguno tiene más fuerza que otro'], correct: 1, explanation: 'El Drop-Base-Rally (caída, pausa, subida explosiva) es el patrón de mayor fuerza.' },
            { q: '¿Por qué pierde efectividad una zona de demanda que ha sido visitada varias veces?', options: ['Porque el precio cambia de sentido con cada visita', 'Porque la orden institucional original probablemente ya se ha llenado', 'Porque las zonas caducan a los 30 días exactos', 'No pierde efectividad, siempre es igual de fuerte'], correct: 1, explanation: 'Una zona visitada múltiples veces probablemente ya vio consumida la orden institucional que la originó.' },
            { q: 'En una zona de rechazo, ¿qué regla evita entrar en falso antes de que la vela termine de formarse?', options: ['Entrar en cuanto se ve la mecha formándose, sin esperar más', 'Esperar siempre el cierre del período antes de entrar', 'Ignorar el contexto de nivel donde aparece', 'Operar solo en timeframes menores a 1h'], correct: 1, explanation: 'Lo que parece un pin bar con tiempo restante puede cambiar antes del cierre — hay que esperar el cierre del período.' },
            { q: '¿Qué distingue a las "manos fuertes" de las "manos débiles" durante una formación de base?', options: ['Las manos fuertes venden con miedo cuando el precio no se mueve', 'Las manos fuertes absorben silenciosamente las ventas de los impacientes', 'Las manos débiles son siempre institucionales', 'No hay diferencia relevante'], correct: 1, explanation: 'Durante la base, los inversores impacientes (manos débiles) venden aburridos; las manos fuertes absorben esas ventas.' },
            { q: '¿Qué patrón de la lección de Formación de Base hace correcciones progresivamente más pequeñas antes de la ruptura?', options: ['Cup & Handle', 'Flat base', 'VCP (Volatility Contraction Pattern)', 'Triangle simétrico'], correct: 2, explanation: 'El VCP se caracteriza por contracciones cada vez menores — el último apretón antes de la ruptura marca la entrada de menor riesgo.' },
            { q: '¿Qué patrón de oferta se considera de máxima fuerza en la tabla de Zonas de Oferta?', options: ['Drop-Base-Drop (DBD)', 'Rally-Base-Drop (RBD)', 'Drop-Base directo', 'Todos tienen la misma fuerza'], correct: 1, explanation: 'El patrón Rally-Base-Drop (subida, pausa, caída fuerte) es el de mayor fuerza en las zonas de oferta.' },
            { q: 'Según el concepto "Rechazo vs rebote normal", ¿qué distingue a un rechazo real?', options: ['Un rechazo siempre ocurre con volumen bajo', 'La velocidad del movimiento y las mechas largas que produce', 'No hay diferencia entre rechazo y rebote', 'El rechazo solo ocurre en gráfico mensual'], correct: 1, explanation: 'Un rechazo genuino se caracteriza por mechas largas: el precio es rechazado con fuerza y cierra lejos de donde intentó llegar.' },
        ]
    },

    6: {
        title: 'Quiz — Comportamiento de Velas',
        questions: [
            { q: '¿Dónde debe colocarse el stop de un engulfing alcista, según la lección?', options: ['Bajo el mínimo de la vela bajista anterior', 'Bajo el mínimo de la propia vela de engulfing', 'En el punto medio del cuerpo de la vela', 'No se necesita stop en este patrón'], correct: 1, explanation: 'El stop va bajo el mínimo de la vela alcista de engulfing — no de la vela bajista previa.' },
            { q: '¿Qué señal de calidad reduce la fiabilidad de un engulfing alcista?', options: ['Que ocurra tras una corrección en tendencia alcista', 'Que se forme con volumen inferior al promedio', 'Que ocurra sobre un soporte relevante', 'Que confirme el fin de una corrección'], correct: 1, explanation: 'Un engulfing con volumen bajo puede ser simplemente ausencia de vendedores, no presencia real de compradores.' },
            { q: 'Estadísticamente, ¿qué patrón tiende a producir movimientos más rápidos según la lección?', options: ['El engulfing alcista, siempre más potente', 'El engulfing bajista, por la asimetría del miedo', 'Ambos son idénticos en potencia', 'Ninguno de los dos, depende solo del volumen'], correct: 1, explanation: 'El pánico de salida cuando las ganancias se borran de golpe hace que los engulfing bajistas tiendan a ser más potentes.' },
            { q: '¿Cuál es la entrada "más elegante" según la lección de Pin Bar, y por qué?', options: ['Al cierre de la vela, siempre', 'La entrada al 50% del cuerpo del pin bar, porque reduce el riesgo sin cambiar el objetivo', 'Esperar la ruptura del extremo opuesto, sin excepción', 'No hay ninguna diferencia entre las entradas'], correct: 1, explanation: 'Entrar al 50% del cuerpo acorta la distancia al stop mientras el objetivo se mantiene, mejorando el R:R.' },
            { q: 'Según la "regla de las tres confluencias", ¿cuántos factores como mínimo debe tener un pin bar de alta probabilidad?', options: ['Uno', 'Dos', 'Al menos tres, de una lista de seis posibles', 'Los seis factores obligatoriamente'], correct: 2, explanation: 'Se necesitan al menos tres de los seis factores de confluencia para que el pin bar sea operativo.' },
            { q: '¿Qué representa un inside bar en términos de psicología de mercado?', options: ['Una señal de reversión inmediata garantizada', 'Una pausa de indecisión — ni compradores ni vendedores tienen convicción suficiente', 'Siempre una continuación de tendencia', 'Un error del gráfico, debe ignorarse'], correct: 1, explanation: 'El inside bar representa un momento de indecisión donde ningún bando supera el rango de la vela anterior.' },
            { q: '¿Qué contexto hace que un inside bar carezca de significado operativo?', options: ['Que aparezca tras un impulso fuerte', 'Que ocurra en un mercado lateralizado sin tendencia clara ni nivel relevante', 'Que ocurra en resistencia', 'Que ocurra en soporte'], correct: 1, explanation: 'Sin contexto (tendencia previa, nivel relevante, vela madre significativa), el inside bar no tiene significado operativo real.' },
        ]
    },

    7: {
        title: 'Quiz — Rupturas de Precio',
        questions: [
            { q: '¿Cuál es el filtro más eficaz para evitar rupturas falsas, según la lección de Ruptura de Rango?', options: ['El color de la vela', 'El volumen frente al promedio de 20 días', 'La hora del día', 'El número de indicadores adicionales'], correct: 1, explanation: 'Si la ruptura viene con volumen inferior al promedio de 20 días, es señal de alerta.' },
            { q: 'Según el "principio de medición", si un rango mide 20 puntos de altura, ¿cuál es el objetivo mínimo tras la ruptura?', options: ['10 puntos por encima del techo', '20 puntos por encima del techo (la misma amplitud del rango)', 'No hay forma de proyectar un objetivo', '40 puntos, el doble de la amplitud'], correct: 1, explanation: 'El principio de medición proyecta un objetivo igual a la amplitud del rango desde el punto de ruptura.' },
            { q: '¿Qué señal invalida inmediatamente una ruptura de rango, según la lección?', options: ['Que el volumen sea alto', 'Que el precio vuelva a entrar dentro del rango con una vela completa (cierre dentro)', 'Que el precio suba dos días seguidos', 'Que aparezca una noticia relacionada'], correct: 1, explanation: 'Si el precio cierra de vuelta dentro del rango, la ruptura ha fallado — hay que salir inmediatamente.' },
            { q: '¿Cuántos toques válidos necesita una línea de tendencia para que su ruptura se considere "muy significativa"?', options: ['1 toque', '2 toques', '3-4 toques', '5 o más toques'], correct: 3, explanation: 'Con 5+ toques válidos, la ruptura es muy significativa y señala posible cambio de tendencia.' },
            { q: 'Si tenías un stop definido por debajo de un soporte que se rompe, ¿qué recomienda la lección de Ruptura de Soporte?', options: ['Mover el stop más abajo para dar más margen', 'Ya saliste automáticamente — analizar si el retest ofrece reentrada', 'Ignorar el stop y mantener la posición', 'Doblar la posición para promediar'], correct: 1, explanation: 'Si el stop estaba bien puesto, ya te sacó de la posición automáticamente.' },
            { q: 'Según la lección de Entradas en Retest, ¿cuál es la ventana de tiempo ideal para que un retest siga siendo válido?', options: ['Dentro de la primera semana tras la ruptura', 'Entre 2 y 3 meses después', 'No hay límite de tiempo', 'Solo el mismo día de la ruptura'], correct: 0, explanation: 'Si el precio tarda más de 2-3 semanas en volver al nivel, este pierde relevancia.' },
            { q: 'En un retest bajista de calidad (tras romper un soporte), ¿qué se espera del volumen en la subida hacia el nivel?', options: ['Alto — más compradores entrando', 'Bajo — corrección sana sin presión compradora real', 'Es irrelevante, no aporta información', 'Debe ser exactamente el mismo que en la ruptura'], correct: 1, explanation: 'En un retest bajista de calidad, el volumen en la subida hacia el nivel roto debería ser bajo.' },
        ]
    },

    8: {
        title: 'Quiz — Análisis de Volumen',
        questions: [
            { q: 'Con volumen en la ruptura superior a 3x el promedio, ¿qué probabilidad de continuación indica la tabla?', options: ['20-30%', '40-50%', '70-80%+', 'No hay relación entre volumen y continuación'], correct: 2, explanation: 'Rupturas con volumen 2x-3x+ del promedio muestran probabilidad de continuación de 70-80% o más.' },
            { q: '¿Cuándo es alcista un retroceso con bajo volumen, según la "regla de contexto del volumen"?', options: ['Nunca, el bajo volumen siempre es señal bajista', 'Cuando ocurre durante correcciones — indica pocos vendedores', 'Solo si ocurre en timeframe mensual', 'Solo si coincide con noticias positivas'], correct: 1, explanation: 'Bajo volumen en una corrección significa pocos vendedores activos — es alcista.' },
            { q: '¿A partir de qué volumen relativo (RVOL) se considera "zona de clímax"?', options: ['1.0x - 1.5x', '1.5x - 2.5x', '3x - 5x', 'Nunca por debajo de 10x'], correct: 2, explanation: 'RVOL de 3x-5x entra en zona de clímax si además coincide con una vela amplia y contexto de tendencia extendida.' },
            { q: '¿Qué distingue un clímax genuino de un pico de volumen rutinario (opex, rebalanceo)?', options: ['El clímax rutinario siempre tiene vela más grande', 'El clímax genuino aparece tras una tendencia extendida, sin necesidad de un evento mecánico puntual', 'No hay ninguna forma de distinguirlos', 'El volumen rutinario siempre es mayor'], correct: 1, explanation: 'El clímax genuino aparece en el contexto de una tendencia ya extendida, sin necesidad de una fecha mecánica detrás.' },
            { q: 'En un "clímax apilado" (segundo clímax en la misma dirección), ¿qué error se destaca como el más costoso?', options: ['Esperar demasiado antes de operar', 'Comprar o vender agresivamente en el primer clímax de la secuencia', 'No usar stop loss', 'Operar en gráfico semanal en vez de diario'], correct: 1, explanation: 'Tratar el primer clímax como definitivo es el error más caro — puede aparecer un segundo clímax mayor.' },
            { q: '¿Dónde va el stop en un trade de clímax bajista, según la sección de gestión de riesgo?', options: ['Justo en el precio de entrada', 'Por debajo del mínimo de la vela de clímax (o de su retest)', 'No se necesita stop en trades de clímax', 'Al 5% fijo sin importar el nivel técnico'], correct: 1, explanation: 'El stop debe ir por debajo del mínimo de la vela de clímax, o de su retest si es más ajustado.' },
            { q: '¿Qué patrón de precio-volumen indica "divergencia bajista" en la lección de Participación Débil?', options: ['Nuevo mínimo de precio con nuevo máximo de volumen', 'Nuevo máximo de precio con volumen decreciente', 'Precio y volumen suben juntos siempre', 'No existe tal patrón'], correct: 1, explanation: 'Divergencia bajista: el precio hace nuevo máximo pero el volumen decrece — precaución, posible techo.' },
            { q: '¿Cómo se recomienda medir correctamente el "volumen relativo" (RVOL)?', options: ['Comparando con el volumen de un solo día anterior', 'Comparando con el promedio de los últimos 20-50 días', 'Comparando con el volumen anual completo', 'No es necesario compararlo con nada'], correct: 1, explanation: 'Usar el promedio de 20-50 días como referencia evita falsos positivos frente a una sola sesión atípica.' },
        ]
    },

    9: {
        title: 'Quiz — Patrones de Gráfico',
        questions: [
            { q: 'Si la resistencia de un triángulo ascendente está en 150 y el mínimo del patrón en 130, ¿cuál es el objetivo mínimo tras la ruptura?', options: ['150', '160', '170', '180'], correct: 2, explanation: 'Altura = 150-130 = 20. Objetivo = ruptura (150) + altura (20) = 170.' },
            { q: '¿Qué probabilidad de ruptura alcista tiene un triángulo ascendente que aparece tras un impulso alcista previo?', options: ['20-30%', '40-50%', '70-80%', '100% garantizado'], correct: 2, explanation: 'Cuando aparece tras un impulso alcista (continuación), la probabilidad de ruptura al alza es del 70-80%.' },
            { q: '¿Qué le ocurre a un triángulo ascendente si aparece dentro de una tendencia bajista mayor?', options: ['Siempre rompe al alza igualmente', 'El contexto de la tendencia mayor determina la dirección esperada — puede romper a la baja', 'Deja de ser un patrón válido', 'Se convierte automáticamente en rectángulo'], correct: 1, explanation: 'El patrón favorece al alza estadísticamente, pero el contexto de tendencia mayor puede dominar.' },
            { q: '¿Qué se debe hacer si tras romper el soporte de un triángulo descendente, el precio cierra de vuelta dentro del patrón?', options: ['Mantener el corto, es normal', 'Salir inmediatamente del corto — es una falsa ruptura', 'Doblar la posición corta', 'Ignorarlo, no cambia nada'], correct: 1, explanation: 'Si el precio cierra de vuelta dentro del triángulo tras la ruptura bajista, es una falsa ruptura.' },
            { q: '¿Qué amplitud mínima se recomienda para operar rebotes dentro de un rectángulo?', options: ['Cualquier amplitud vale', 'Al menos 5% (evitar rectángulos muy estrechos)', 'Al menos 50%', 'No importa la amplitud del rectángulo'], correct: 1, explanation: 'En rectángulos de menos del 5% de amplitud, el ratio riesgo/recompensa suele ser desfavorable.' },
            { q: '¿Qué representa el "asta" en el patrón bandera y asta?', options: ['La consolidación tras el impulso', 'El movimiento fuerte inicial, desde el inicio del impulso hasta el inicio de la bandera', 'El objetivo de precio del patrón', 'El volumen de la ruptura'], correct: 1, explanation: 'El asta es el movimiento fuerte inicial; la bandera es la consolidación posterior.' },
            { q: 'Si una bandera retrocede más del 61.8% del asta, ¿qué implica según la advertencia de la lección?', options: ['Es una señal aún más fiable', 'Sigue funcionando pero la probabilidad de éxito baja significativamente', 'El patrón se invalida por completo automáticamente', 'No tiene ningún efecto en la fiabilidad'], correct: 1, explanation: 'Una corrección tan profunda reduce la probabilidad de éxito del patrón, aunque puede seguir funcionando.' },
        ]
    },

    10: {
        title: 'Quiz — Alineación Multi-Temporalidad',
        questions: [
            { q: '¿Qué acción corresponde a un "primer LL en mensual" según la tabla de señales de sesgo mensual?', options: ['Reducir posiciones largas al 50%', 'Cambio de sesgo a bajista confirmado — definitivo', 'No hacer nada, es solo ruido', 'Aumentar exposición larga'], correct: 1, explanation: 'El primer LL en mensual tiene peso "definitivo": confirma el cambio de sesgo a bajista.' },
            { q: '¿Qué rol cumple el sesgo mensual según el concepto "El sesgo como filtro, no como señal"?', options: ['Indica el momento exacto de entrada', 'Filtra qué tipo de operaciones considerar (solo longs, solo cortos, o ninguna)', 'Sustituye completamente al análisis diario', 'Solo se usa una vez al año'], correct: 1, explanation: 'El sesgo mensual no da timing de entrada — filtra qué tipo de operaciones buscar.' },
            { q: 'Con sesgo mensual alcista y estructura semanal "bajista fuerte (LH+LL)", ¿qué decisión indica la tabla?', options: ['Buscar longs con alta convicción', 'Posible cambio de sesgo — reducir exposición', 'Vender en corto agresivamente sin más análisis', 'Ignorar el semanal por completo'], correct: 1, explanation: 'Cuando el semanal contradice fuertemente al mensual alcista, la tabla indica precaución.' },
            { q: 'Con alineación M↑ + S↑ + D setup (triple alineación), ¿qué tamaño de posición sugiere la tabla de Setup Diario?', options: ['25-30%', '50-60%', '100% (máximo)', '0.25%'], correct: 2, explanation: 'La triple alineación mensual-semanal-diario permite el tamaño de posición completo.' },
            { q: 'Si el setup identificado es mensual, ¿en qué timeframe se busca el trigger de entrada, según la tabla?', options: ['En el propio mensual', 'En semanal', 'Directamente en 15 minutos', 'No se necesita trigger si el setup es mensual'], correct: 1, explanation: 'Para un setup en mensual, el trigger se busca un nivel por debajo: en el semanal.' },
            { q: '¿Qué principio resume el concepto "Sin trigger no hay entrada"?', options: ['Siempre hay que anticipar el trigger antes de que se confirme', 'Aunque el precio suba sin ti, no entras sin la señal de trigger definida', 'El trigger es opcional si el análisis es muy convincente', 'El trigger solo aplica en timeframes mayores'], correct: 1, explanation: 'No se entra aunque el precio se mueva sin ti si la señal definida no ha aparecido.' },
            { q: '¿Qué mal hábito describe "cambiar el trigger sobre la marcha"?', options: ['Una técnica válida de gestión de riesgo', 'Inventar un trigger más fácil de cumplir para forzar la entrada', 'Esperar la confirmación completa antes de actuar', 'Documentar el trigger en el plan de trade'], correct: 1, explanation: 'Cambiar el trigger para justificar una entrada ya deseada es un error de disciplina.' },
            { q: '¿Cuándo se construye la watchlist, según la lección 10-5?', options: ['Cada mañana antes de la apertura', 'Una vez por semana, el domingo, como parte de la rutina de revisión', 'Solo cuando el mercado está muy volátil', 'No tiene un momento fijo, se hace por intuición'], correct: 1, explanation: 'La watchlist se construye el domingo; entre semana solo se hacen ajustes menores y excepcionales.' },
            { q: '¿Cuál es el tamaño recomendado de la watchlist semanal?', options: ['1-2 activos', '5-10 activos', '20-30 activos', 'Cuantos más, mejor'], correct: 1, explanation: 'Menos de 5 puede dejarte sin oportunidades; más de 10-12 satura la capacidad real de vigilar cada zona.' },
        ]
    },

    11: {
        title: 'Quiz — Planificación del Trade',
        questions: [
            { q: 'Con R:R 1:2, ¿qué porcentaje de aciertos se necesita aproximadamente para llegar a breakeven, según la tabla?', options: ['55%', '35%', '27%', '18%'], correct: 1, explanation: 'Con R:R 1:2, alrededor del 35% de aciertos ya alcanza el breakeven.' },
            { q: '¿Qué se define ANTES según el orden correcto que exige la lección de Definir el Setup?', options: ['El objetivo, antes que el stop', 'El stop, antes que el objetivo', 'El tamaño de posición, antes que el análisis', 'Ninguno de los dos importa el orden'], correct: 1, explanation: 'El stop lo fija el mercado; el objetivo lo fija la estructura técnica. El orden es siempre stop primero.' },
            { q: 'Capital $50.000, riesgo máximo 1% ($500), entrada $100, stop $95 (distancia $5), ¿cuántas acciones se compran?', options: ['50 acciones', '100 acciones', '500 acciones', '1000 acciones'], correct: 1, explanation: '$500 (riesgo máximo) / $5 (distancia al stop) = 100 acciones.' },
            { q: 'Con un setup A+ (triple alineación MTF), ¿cuál es el riesgo máximo permitido según la tabla de Tamaño de Posición?', options: ['0.5%', '1%', '1.5%', '2%'], correct: 3, explanation: 'Un setup A+ con triple alineación permite hasta 2% de riesgo máximo — el nivel más alto de la tabla.' },
            { q: '¿Qué es el "test del sueño" según el tip de Tamaño de Posición?', options: ['Dormir antes de decidir el tamaño de una posición', 'Si una posición te impide dormir, es demasiado grande — reduce el tamaño', 'Un test técnico para medir volatilidad nocturna', 'Una regla exclusiva para posiciones cortas'], correct: 1, explanation: 'Si una posición genera ansiedad que impide dormir, es señal de que el tamaño es excesivo.' },
            { q: 'Según la matemática del riesgo fijo, ¿aproximadamente cuántos stops consecutivos al 2% se necesitan para perder el 50% de la cuenta?', options: ['7', '15', '34', '100'], correct: 2, explanation: 'Con 2% de riesgo por trade, hacen falta unos 34 stops consecutivos para perder el 50% de la cuenta.' },
            { q: '¿Qué es un "time stop", según el Plan de Trade?', options: ['Un stop de precio muy ajustado', 'Salir si en X días el precio no ha avanzado hacia el objetivo, aunque el stop de precio no haya saltado', 'Un stop que solo se activa de noche', 'Un tipo de orden exclusiva de criptomonedas'], correct: 1, explanation: 'El time stop libera capital estancado si el trade no progresa en el plazo definido.' },
        ]
    },

    12: {
        title: 'Quiz — Gestión del Riesgo',
        questions: [
            { q: '¿Qué riesgo por trade recomienda la tabla para un trader "empezando (<1 año)"?', options: ['0.25-0.5%', '1-1.5%', 'Hasta 2%', '5%'], correct: 0, explanation: 'Para traders con menos de un año de experiencia, se recomienda 0.25-0.5% de riesgo por trade.' },
            { q: 'Si la cuenta cae un 20% desde el máximo, ¿qué recomienda la regla de "reducción automática"?', options: ['Aumentar el riesgo para recuperar más rápido', 'Reducir el riesgo a la mitad', 'Parar de operar completamente durante una semana y revisar el proceso', 'No cambiar nada'], correct: 2, explanation: 'Con -20% la regla indica parar completamente durante una semana y revisar el proceso.' },
            { q: 'Una pérdida del 50% de la cuenta, ¿qué ganancia porcentual requiere para recuperarse?', options: ['50%', '75%', '100%', '150%'], correct: 2, explanation: 'Debido a la asimetría matemática de las pérdidas, recuperar un -50% exige un +100%.' },
            { q: 'Según el trailing con EMA21, ¿qué porcentaje del movimiento total de una tendencia suele capturar este método?', options: ['10-20%', '30-40%', '60-70%', '100%'], correct: 2, explanation: 'Usar el cierre bajo la EMA21 como trailing stop suele capturar el 60-70% del movimiento total.' },
            { q: 'Tras 4 stops consecutivos, ¿qué acción indica la tabla de Revenge Trading y Racha Perdedora?', options: ['Aumentar el tamaño para recuperar rápido', 'Reducir el tamaño al 50%', 'Parar completamente sin excepción', 'Ninguna acción especial'], correct: 1, explanation: 'Tras 4 stops consecutivos, la tabla indica reducir el tamaño al 50%.' },
            { q: '¿Cuál es el límite máximo de riesgo total de cartera recomendado si todos los stops saltaran el mismo día?', options: ['1%', '3-5%', '10%', 'No hay límite recomendado'], correct: 1, explanation: 'Se recomienda un límite razonable de 3-5% del capital total como riesgo máximo simultáneo.' },
            { q: '¿Qué caracteriza una diversificación real, según el concepto de Protección de Capital?', options: ['Tener muchos activos del mismo sector', 'Tener activos con baja correlación entre sí, en distintos sectores', 'Comprar solo un único activo', 'Diversificar solo entre criptomonedas'], correct: 1, explanation: 'La diversificación real busca baja correlación entre activos de distintos sectores.' },
        ]
    },

    13: {
        title: 'Quiz — Ejecución',
        questions: [
            { q: '¿Qué tasa de éxito aproximada tiene una entrada "por FOMO" según la tabla de Entradas Prematuras?', options: ['55-65%', '45-55%', '30-40%', '70%+'], correct: 2, explanation: 'Las entradas por FOMO tienen la tasa de éxito más baja de la tabla: 30-40%.' },
            { q: '¿Qué propone la "técnica de los 10 minutos" ante un impulso de entrar antes del trigger?', options: ['Entrar inmediatamente para no perder la oportunidad', 'Esperar 10 minutos sin tocar nada, dejando que el impulso emocional se reduzca', 'Cerrar la plataforma durante una semana', 'Consultar con otros traders antes de decidir'], correct: 1, explanation: 'Esperar 10 minutos sin actuar suele reducir significativamente el impulso emocional.' },
            { q: '¿Qué representa el "plan como contrato" con tu yo futuro, según la lección de Seguir el Plan?', options: ['Un documento legal vinculante con el broker', 'Un contrato del yo racional (antes de entrar) con el yo emocional (durante el trade)', 'Una promesa que se puede romper si el instinto lo dice', 'Un contrato solo válido en trades ganadores'], correct: 1, explanation: 'El plan es un contrato del yo racional de antes de entrar, diseñado para resistir la presión emocional.' },
            { q: '¿Cuál de estas SÍ es una razón legítima para desviarse del plan, según la tabla?', options: ['Una corazonada de que el precio va a rebotar', 'Una noticia material inesperada que invalida la tesis original', 'Estar nervioso por la posición', 'Un tweet bajista'], correct: 1, explanation: 'Solo eventos objetivos como una noticia material inesperada justifican desviarse — no las corazonadas.' },
            { q: '¿Qué mide la "tasa de adherencia al plan" recomendada como métrica mensual?', options: ['El porcentaje de trades ganadores', 'El porcentaje de veces que se siguió el plan al 100%', 'El número total de trades realizados', 'La rentabilidad total del mes'], correct: 1, explanation: 'El objetivo no es ganar todos los trades — es seguir el plan en el 95%+ de las ocasiones.' },
            { q: 'Según "Tener razón vs ganar dinero", ¿qué es cierto sobre el trading?', options: ['Tener razón sobre la dirección garantiza ganar dinero', 'Se puede tener razón sobre la dirección y aun así perder dinero por mala ejecución', 'Ganar dinero siempre implica haber tenido razón', 'No existe relación entre acertar y ganar'], correct: 1, explanation: 'El objetivo del trading no es tener razón, es ser rentable con la ejecución.' },
            { q: 'Tras un stop ejecutado según el plan, ¿qué recomienda la lección de Salir Sin Ego?', options: ['Revisar el gráfico inmediatamente para reentrar por venganza', 'No revisar el gráfico durante 30 minutos, para evitar el impulso de re-entrar', 'Doblar la siguiente posición para compensar', 'Abandonar el trading por el día siguiente completo'], correct: 1, explanation: 'Dejar pasar 30 minutos sin mirar el gráfico ayuda a evitar el impulso de reentrar por venganza.' },
        ]
    },

    14: {
        title: 'Quiz — Trampas del Mercado',
        questions: [
            { q: '¿Qué volumen caracteriza típicamente una falsa ruptura, según la tabla?', options: ['Alto, superior a 1.5x el promedio', 'Bajo o normal', 'Siempre exactamente el doble del promedio', 'El volumen no distingue rupturas reales de falsas'], correct: 1, explanation: 'Las falsas rupturas suelen venir con volumen bajo o normal, a diferencia de las reales.' },
            { q: '¿Qué es el "stop hunt", según el concepto de Falsas Rupturas?', options: ['Un tipo de orden automática del broker', 'Empujar brevemente el precio a través de un nivel obvio para activar los stops agrupados ahí', 'Una estrategia de gestión de cartera', 'Un patrón de velas japonesas'], correct: 1, explanation: 'Los niveles muy obvios concentran muchos stops — instituciones pueden empujar el precio brevemente a través de ellos.' },
            { q: 'Con el precio extendido más de un 20% sobre la MA20, ¿qué sugiere la tabla de Entradas Tardías?', options: ['Es el mejor momento para entrar con tamaño completo', 'Probable sobrecompra de corto plazo — riesgo de pullback', 'Señal de continuación garantizada', 'No tiene ninguna implicación'], correct: 1, explanation: 'Un precio muy extendido sobre su media de corto plazo suele indicar sobrecompra y mayor riesgo de pullback.' },
            { q: '¿Cuál de estas opciones NO es una alternativa recomendada ante una entrada tardía?', options: ['Esperar el primer pullback', 'Reducir el tamaño si se decide entrar igualmente', 'Dejarlo pasar y buscar el siguiente setup', 'Perseguir el movimiento con tamaño completo cuanto antes'], correct: 3, explanation: 'Perseguir el movimiento con tamaño completo es justo lo que la lección advierte evitar.' },
            { q: 'Según el concepto "Actividad vs productividad", ¿qué ocurre con el número de trades en trading?', options: ['Más trades siempre generan más ganancias, como en otros trabajos', 'Más trades frecuentemente significan lo contrario, por menor calidad promedio', 'No hay relación entre cantidad y calidad de trades', 'El número ideal de trades es siempre el máximo posible'], correct: 1, explanation: 'A diferencia de otros trabajos, en trading más actividad no equivale a más resultado.' },
            { q: '¿Cuál de estas NO aparece como causa típica de sobretrading en la tabla?', options: ['Aburrimiento en mercados laterales', 'Revenge trading tras pérdidas', 'Sobreconfianza tras una racha ganadora', 'Seguir estrictamente el plan de trading'], correct: 3, explanation: 'Seguir el plan es justo lo contrario del sobretrading.' },
            { q: '¿Qué implica un "volumen clímax en mínimos", según la tabla de Ignorar el Volumen?', options: ['Continuación segura de la caída', 'Posible capitulación — suelo cercano', 'Señal irrelevante sin contexto', 'Siempre una ruptura falsa'], correct: 1, explanation: 'Un clímax de volumen en mínimos sugiere posible capitulación y cercanía de un suelo.' },
        ]
    },

    15: {
        title: 'Quiz — Revisión Post-Trade',
        questions: [
            { q: '¿Qué es el "sesgo retrospectivo" (hindsight bias) según la lección de Captura de Pantalla?', options: ['Analizar el pasado con datos objetivos', 'El cerebro reescribe cómo "deberías haber sabido" el resultado, una vez ya lo conoces', 'Un sesgo que solo afecta a traders principiantes', 'Un tipo de indicador técnico'], correct: 1, explanation: 'Una vez conocido el resultado, el cerebro reescribe la historia haciendo parecer obvio lo que no lo era.' },
            { q: '¿Cuál de estas situaciones se clasifica como ERROR, aunque el resultado final fuera ganador?', options: ['Plan seguido, stop ejecutado, pérdida', 'Entrada sin confirmación que resultó ganadora', 'Plan seguido al 100%, resultó pérdida', 'Objetivo alcanzado según el plan'], correct: 1, explanation: 'Entrar sin confirmación es un error de proceso, independientemente del resultado.' },
            { q: '¿Qué frecuencia recomienda la lección para revisar y agrupar los errores registrados por categoría?', options: ['Cada día', 'El primer domingo de cada mes', 'Solo una vez al año', 'Nunca es necesario agrupar'], correct: 1, explanation: 'Revisar mensualmente permite identificar el patrón de error más frecuente como prioridad de mejora.' },
            { q: '¿Qué principio resume "El edge es personal", según la lección de Revisión del Setup?', options: ['Todos los traders deben usar la misma estrategia exacta', 'Dos traders con la misma estrategia pueden tener resultados distintos según su capacidad de ejecutarla', 'No existe el concepto de edge personal', 'El edge depende únicamente del capital inicial'], correct: 1, explanation: 'No hay que perseguir "la mejor estrategia" sino identificar en qué setups cada trader personalmente rinde mejor.' },
            { q: '¿Cuál es, según la lección, la diferencia más consistente entre traders rentables a largo plazo y los que abandonan?', options: ['La inteligencia', 'El capital inicial disponible', 'La disciplina de revisar sistemáticamente y ajustar el proceso', 'La suerte en los primeros meses'], correct: 2, explanation: 'La disciplina de revisión sistemática, no la inteligencia ni el capital inicial, es el factor diferenciador.' },
            { q: 'Antes de formular una regla personal a partir de un patrón detectado en el journal, ¿qué tamaño mínimo de muestra recomienda la lección?', options: ['2-3 trades', '10-15 trades', '100 trades', 'No hace falta ninguna muestra mínima'], correct: 1, explanation: 'Se recomienda verificar que el patrón se mantiene con al menos 10-15 trades antes de convertirlo en regla.' },
            { q: '¿Qué contiene la sección "Mis condiciones óptimas" del documento de Lecciones Aprendidas?', options: ['Los errores más frecuentes', 'El estado de mercado, hora del día y contexto donde el trader rinde mejor', 'La lista de brokers recomendados', 'El historial completo de operaciones'], correct: 1, explanation: 'Esa sección documenta las condiciones específicas donde el propio trader obtiene mejores resultados.' },
        ]
    },

    16: {
        title: 'Quiz — Las 4 Etapas (Weinstein)',
        questions: [
            { q: '¿En qué timeframe se recomienda identificar las 4 etapas de Weinstein, y por qué?', options: ['Diario, porque tiene más detalle', 'Semanal, porque filtra el ruido de movimientos de varios meses', 'Horario, para mayor precisión', 'Mensual únicamente'], correct: 1, explanation: 'El diario tiene demasiado ruido para identificar etapas de varios meses; el semanal, con la MA de 30 semanas, lo filtra.' },
            { q: '¿Es la Etapa 1 (Acumulación) por sí sola una señal de compra según Weinstein?', options: ['Sí, siempre que dure más de un mes', 'No — es fase de espera y observación, la señal llega con la ruptura a Etapa 2', 'Sí, es la mejor etapa para comprar agresivamente', 'Depende únicamente del volumen'], correct: 1, explanation: 'La Etapa 1 no es señal de entrada — la señal de compra llega con la ruptura confirmada hacia la Etapa 2.' },
            { q: '¿Qué hace la media de 30 semanas al iniciarse la Etapa 2?', options: ['Se aplana completamente', 'Gira claramente hacia arriba y queda por debajo del precio', 'Cruza por encima del precio', 'Desaparece del gráfico'], correct: 1, explanation: 'En la Etapa 2 la media de 30 semanas gira al alza y queda por debajo del precio como soporte dinámico.' },
            { q: 'Según "la regla simple de Weinstein", ¿qué se hace si el precio cae claramente por debajo de la MA de 30 semanas en Etapa 2?', options: ['Ignorarlo, es ruido normal', 'Considerar tomar beneficios o poner la posición en alerta máxima', 'Añadir a la posición inmediatamente', 'Cambiar a un timeframe menor para decidir'], correct: 1, explanation: 'Sugiere que la acción puede estar entrando en Etapa 3 — momento de considerar tomar beneficios.' },
            { q: 'Para un trader de corto-medio plazo, ¿qué acción recomienda la lección durante la Etapa 3 (Distribución)?', options: ['Aumentar posición, la tendencia sigue intacta', 'Tomar beneficios — el motivo principal para mantener (la tendencia) ya no está presente', 'Esperar indefinidamente sin actuar', 'Vender en corto inmediatamente sin confirmación'], correct: 1, explanation: 'Para el trader de corto-medio plazo, la Etapa 3 pide tomar beneficios.' },
            { q: 'En la Etapa 4, ¿qué función cumple la media de 30 semanas respecto al precio?', options: ['Soporte dinámico, igual que en Etapa 2', 'Resistencia dinámica, por encima del precio, bajando o plana', 'No tiene ninguna función en esta etapa', 'Se convierte en el objetivo de precio'], correct: 1, explanation: 'En la Etapa 4 la MA30 semanas queda por encima del precio y actúa como resistencia dinámica.' },
            { q: '¿Qué pregunta es la correcta para evaluar si el declive de la Etapa 4 ha terminado, según la lección?', options: ['¿Cuánto ha caído el precio?', '¿Ha hecho la transición estructural de Etapa 4 a Etapa 1 (rango lateral)?', '¿Cuántos días lleva cayendo?', '¿Qué dicen las noticias sobre la empresa?'], correct: 1, explanation: 'La pregunta correcta es si ha hecho la transición estructural a un rango lateral (Etapa 1), no cuánto ha caído.' },
        ]
    },

    17: {
        title: 'Quiz — El Mercado Descuenta Información',
        questions: [
            { q: '¿Qué significa realmente "descontar" un evento futuro, según el concepto de la lección?', options: ['Predecir con certeza absoluta el resultado', 'Incorporar al precio actual la probabilidad ponderada de los distintos resultados posibles', 'Ignorar el evento hasta que ocurra', 'Bajar el precio automáticamente antes del evento'], correct: 1, explanation: 'Descontar es incorporar al precio actual una probabilidad ponderada de resultados, no una predicción certera.' },
            { q: '¿Por qué "esta empresa va a tener un trimestre excelente" puede no ser información explotable?', options: ['Porque las empresas nunca tienen buenos trimestres', 'Porque si ya es el consenso del mercado, ya está reflejado en el precio', 'Porque los trimestres excelentes bajan siempre el precio', 'Porque el precio nunca refleja expectativas'], correct: 1, explanation: 'Lo relevante no es si irá bien, sino si irá MEJOR de lo que el mercado ya espera.' },
            { q: 'En la fase "tardía" de un rumor, según la tabla de Buy the Rumour, ¿quién participa típicamente?', options: ['Solo analistas especializados', 'Fondos sectoriales exclusivamente', 'Público general y redes sociales, con FOMO', 'Nadie, la fase tardía no tiene participación'], correct: 2, explanation: 'En la fase tardía participa el público general con FOMO — la mejor relación riesgo-recompensa ya ha pasado.' },
            { q: 'Si un resultado "cumple exactamente lo descontado" (ni mejor ni peor), ¿qué reacción de precio es la típica?', options: ['Subida fuerte adicional', 'Caída o lateral — el clásico "sell the news"', 'Ninguna reacción en absoluto', 'Siempre sube con fuerza'], correct: 1, explanation: 'Cumplir exactamente lo esperado, sin sorpresa, suele producir caída o lateralidad.' },
            { q: '¿Qué mueve realmente el precio tras un evento, según el concepto de "sorpresa relativa"?', options: ['Si el resultado fue bueno o malo en términos absolutos', 'Si fue mejor o peor que lo que el mercado ya tenía descontado', 'El tamaño de la empresa', 'La hora del día del anuncio'], correct: 1, explanation: 'Lo que mueve el precio es la sorpresa relativa frente a la expectativa ya descontada.' },
            { q: '¿En qué momento la reacción del precio a unos earnings suele ser "más informada" según la tabla?', options: ['En los primeros minutos after-hours', 'Durante la conference call, exclusivamente', 'En la apertura del día siguiente, con mayor liquidez', 'Nunca es más informada, siempre es igual de errática'], correct: 2, explanation: 'La apertura del día siguiente ofrece mayor liquidez y una reacción más consolidada.' },
            { q: '¿Por qué el guidance suele mover más el precio que el resultado del trimestre ya pasado?', options: ['Porque el guidance nunca se cumple', 'Porque el trimestre pasado ya era información anticipable, mientras el guidance aporta información nueva sobre el futuro', 'Porque los inversores ignoran el guidance', 'No hay diferencia real entre ambos'], correct: 1, explanation: 'El resultado pasado ya podía anticiparse; el guidance aporta información genuinamente nueva sobre el futuro.' },
        ]
    },

    18: {
        title: 'Quiz — Risk/Reward',
        questions: [
            { q: 'En el ejemplo comparativo de la lección 18-1, ¿cuál es el R:R al comprar en la zona de demanda a $100 con stop en $98.50, frente al objetivo de $120?', options: ['1:5', '1:8', '1:13.3', '1:20'], correct: 2, explanation: 'Con riesgo de 1.5% hasta un recorrido de $20, el R:R resultante es 1:13.3.' },
            { q: '¿Qué característica distingue a una "zona fuerte" de una "débil" en la tabla de Anatomía de Zona de Demanda?', options: ['El color con el que está marcada en el gráfico', 'La velocidad y contundencia del rechazo, y el volumen asociado', 'La hora del día en que se formó', 'El nombre del bróker usado'], correct: 1, explanation: 'Una zona fuerte muestra una reversión rápida y marcada, con volumen notablemente superior al promedio.' },
            { q: '¿Dónde va exactamente el stop respecto a una zona de demanda bien delimitada?', options: ['En mitad de la zona', 'Justo por debajo del límite inferior de la zona', 'Muy por encima del límite superior', 'No se necesita stop si la zona es de calidad'], correct: 1, explanation: 'El límite inferior de la zona es donde va el stop — no en mitad de ella.' },
            { q: 'Comprar en "tierra de nadie" (sin nivel técnico cercano), ¿qué efecto psicológico tiende a generar?', options: ['Ninguno, es igual que comprar en zona de demanda', 'Mayor probabilidad de mover el stop por miedo, al no tener margen ni respaldo técnico', 'Mayor tranquilidad porque el precio "puede ir a cualquier lado"', 'Solo afecta a traders principiantes'], correct: 1, explanation: 'Sin margen técnico, cualquier fluctuación normal genera ansiedad y tentación de mover el stop.' },
            { q: 'Según "Buena zona no es sinónimo de buen trade", ¿qué puede invalidar una zona de demanda de calidad como trade operable?', options: ['Que tenga pocos toques previos', 'Que la resistencia inmediatamente encima deje poco espacio hasta el siguiente nivel relevante', 'Que coincida con tendencia mayor a favor', 'Que tenga alto volumen en el rechazo'], correct: 1, explanation: 'Una zona excelente sin espacio hasta el siguiente nivel relevante no es necesariamente un trade que merezca ejecutarse ahora.' },
            { q: '¿Qué pregunta propone la lección hacerse ANTES que "¿qué R:R tiene este trade?"?', options: ['¿Cuánto dinero tengo disponible?', '¿Estoy comprando en una zona de demanda real y de calidad, o en tierra de nadie?', '¿Qué dicen los analistas sobre este activo?', '¿Cuál es el volumen promedio del último mes?'], correct: 1, explanation: 'Si la zona es de calidad, el buen R:R suele derivarse naturalmente de ahí.' },
            { q: '¿Qué diferencia esencial resume aplicar el R:R "desde la zona, no desde la calculadora"?', options: ['El R:R es simplemente un cálculo matemático arbitrario', 'El buen R:R es consecuencia de dónde compras (la zona), no un número que se ajusta a voluntad', 'No existe diferencia real entre ambos enfoques', 'La calculadora siempre da mejores resultados que el análisis de zonas'], correct: 1, explanation: 'El R:R favorable no se fabrica ajustando el stop artificialmente — surge de comprar en el lugar correcto.' },
        ]
    },

    19: {
        title: 'Quiz — Métodos de Confirmación de Entrada',
        questions: [
            { q: '¿Qué diferencia hay entre una simple ruptura de línea de tendencia y una reversión confirmada?', options: ['Son exactamente lo mismo', 'La ruptura puede ser ruido; la reversión exige que se forme una nueva estructura reconocible en la dirección contraria', 'La reversión ocurre siempre antes que la ruptura', 'No hay forma de distinguirlas'], correct: 1, explanation: 'Una ruptura aislada puede ser solo una mecha de rechazo; la reversión requiere una estructura nueva que confirme el cambio.' },
            { q: '¿Qué recomienda la lección sobre el retest de una resistencia recién rota, ahora convertida en soporte?', options: ['Ignorarlo, no aporta información', 'Suele ofrecer mejor R:R que perseguir la ruptura inicial', 'Vender inmediatamente al llegar el precio ahí', 'Es siempre una señal bajista'], correct: 1, explanation: 'El retest del nivel roto suele dar una entrada con mejor relación riesgo/recompensa que perseguir la ruptura inicial.' },
            { q: 'Según la tabla de niveles de Fibonacci, ¿qué interpretación tiene un retroceso al 62%?', options: ['Retroceso superficial, tendencia muy fuerte', 'Retroceso intermedio, punto de equilibrio', 'Retroceso profundo — última zona razonable antes de cuestionar la tendencia', 'Nivel sin ningún significado'], correct: 2, explanation: 'El 62% se interpreta como retroceso profundo — el límite razonable antes de cuestionar si la tendencia sigue vigente.' },
            { q: '¿Qué distingue a una consolidación de calidad frente a una pausa débil o de indecisión?', options: ['La consolidación de calidad tiene rango errático y volumen creciente', 'La consolidación de calidad tiene rango progresivamente más estrecho y volumen decreciente', 'No hay diferencia real entre ambas', 'La pausa débil siempre dura más tiempo'], correct: 1, explanation: 'Una consolidación de calidad muestra contracción progresiva del rango y volumen decreciente.' },
            { q: 'Un gap de agotamiento (EG), ¿dónde suele aparecer típicamente?', options: ['Al salir de una consolidación, al inicio de una tendencia', 'En mitad de una tendencia ya activa', 'Tras un movimiento ya extendido — posible fase final antes de reversión', 'Nunca aparece en tendencias reales'], correct: 2, explanation: 'El gap de agotamiento aparece tras un movimiento ya muy extendido, sugiriendo una posible fase final.' },
            { q: 'Según "La posición en el movimiento es la clave", ¿qué determina el significado de un gap?', options: ['El tamaño exacto del gap en puntos', 'El momento del movimiento en que aparece (inicio, mitad, o final ya extendido)', 'El color de la vela del gap', 'La hora exacta de apertura del mercado'], correct: 1, explanation: 'El mismo salto de precio puede significar el inicio de una tendencia o su final, según en qué fase aparece.' },
            { q: '¿Qué distingue al Volume Trend (VT) del Volume Climax (VC), según la tabla de la lección 19-6?', options: ['El VT indica agotamiento, el VC indica salud', 'El VT es respaldo creciente y saludable durante el desarrollo; el VC es posible agotamiento tras una extensión considerable', 'Son términos intercambiables', 'El VC ocurre siempre al principio de la tendencia'], correct: 1, explanation: 'El VT saludable acompaña el desarrollo normal de la tendencia; el VC aparece tras una extensión ya considerable.' },
            { q: '¿Qué característica debe tener un volumen de tendencia saludable, según "Participación creciente, no explosiva"?', options: ['Ser espectacular en una sola sesión concreta', 'Ir aumentando de forma consistente en la dirección del precio, sin necesidad de ser explosivo en un día', 'Ser siempre decreciente', 'No tiene relación con la salud de la tendencia'], correct: 1, explanation: 'No hace falta un pico espectacular — lo relevante es que la tendencia del volumen vaya creciendo de forma consistente.' },
        ]
    },

    20: {
        title: 'Quiz — RSU Score Explicado',
        questions: [
            { q: '¿Cuántos puntos máximo aporta cada uno de los 5 factores del RSU Score?', options: ['10', '20', '25', '50'], correct: 1, explanation: 'El RSU Score reparte 100 puntos en 5 bloques de 20 puntos: crecimiento de ingresos, ROE, margen neto, consenso de analistas y potencial de precio objetivo.' },
            { q: '¿A partir de qué score se muestra la etiqueta "COMPRA FUERTE"?', options: ['≥50', '≥65', '≥80', '100 exacto'], correct: 2, explanation: 'COMPRA FUERTE aparece a partir de 80 puntos; entre 65 y 79 la etiqueta es COMPRA.' },
            { q: '¿El Piotroski F-Score forma parte del cálculo del RSU Score?', options: ['Sí, aporta el 20% del score final', 'No — son dos tarjetas independientes con escalas distintas (0-100 y 0-9)', 'Solo en algunos sectores', 'Sí, pero solo si el ticker tiene buena liquidez'], correct: 1, explanation: 'En la versión actual de la terminal, RSU Score y Piotroski son indicadores independientes, no un score combinado.' },
            { q: 'En el Piotroski, si yfinance no reporta una línea contable, ¿cómo se marca ese criterio?', options: ['Con una X roja, como si no lo cumpliera', 'Con un guion gris "–", indicando dato no disponible (y no suma el punto)', 'Se omite el criterio por completo de la lista', 'Se asume que sí lo cumple'], correct: 1, explanation: 'El guion gris distingue "no lo sabemos" de "lo sabemos y no pasa el criterio" — en ambos casos no suma el punto.' },
            { q: 'En la comparativa sectorial, para métricas de valoración como el P/E, ¿cuándo se marca como "favorable"?', options: ['Cuando está por encima de la mediana del sector', 'Cuando está por debajo de la mediana del sector', 'Favorable no aplica a métricas de valoración', 'Solo si el sector tiene más de 50 empresas'], correct: 1, explanation: 'Para valoración, estar por debajo de la mediana del sector es favorable; para rentabilidad y crecimiento es al revés.' },
            { q: '¿Cuál es el orden de lectura recomendado en el flujo de Research, según la lección 20-4?', options: ['Técnico primero, fundamentales al final', 'RSU Score → Piotroski → Sector → Insiders → Institucional → Técnico, al final', 'Solo mirar el RSU Score y nada más', 'Insiders primero, siempre'], correct: 1, explanation: 'El flujo prioriza fundamentales y sentimiento, dejando la estructura técnica para el último paso.' },
            { q: 'Con RSU Score alto pero Piotroski bajo (<4), ¿qué lectura recomienda la lección?', options: ['Confiar ciegamente en el RSU Score', 'Revisar calidad del beneficio y dilución antes de confiar en el score', 'Ignorar ambos indicadores', 'Es siempre señal de compra fuerte'], correct: 1, explanation: 'Esa combinación pide revisar si el beneficio se traduce en caja real y si hay dilución.' },
        ]
    },

    21: {
        title: 'Quiz — Análisis Fundamental',
        questions: [
            { q: 'En el estado de resultados trimestral de Research, ¿qué orden siguen las 4 magnitudes en cascada?', options: ['Beneficio Neto → Beneficio Operativo → Beneficio Bruto → Ingresos', 'Ingresos → Beneficio Bruto → Beneficio Operativo → Beneficio Neto', 'Beneficio Bruto → Ingresos → Beneficio Neto → Beneficio Operativo', 'No hay un orden definido'], correct: 1, explanation: 'Cada línea resta un bloque de costes distinto: Ingresos, menos COGS = Bruto, menos gastos operativos = Operativo, menos intereses/impuestos = Neto.' },
            { q: 'Según el patrón CAN SLIM de aceleración, ¿qué se busca al comparar varios trimestres de ingresos?', options: ['Que los ingresos sean siempre exactamente iguales', 'Que la tasa de crecimiento del trimestre actual sea mayor que la de trimestres anteriores', 'Que los ingresos bajen de forma controlada', 'Solo importa el último trimestre, nada más'], correct: 1, explanation: 'CAN SLIM busca aceleración: no solo crecimiento, sino que ese crecimiento vaya a más trimestre a trimestre.' },
            { q: 'Un ROE muy alto combinado con un D/E Ratio muy elevado, ¿qué advertencia sugiere la lección?', options: ['Es siempre una señal excelente sin matices', 'La rentabilidad puede depender del apalancamiento, no solo de la eficiencia del negocio', 'El D/E Ratio no tiene relación con el ROE', 'Hay que ignorar el D/E Ratio en este caso'], correct: 1, explanation: 'Un ROE alto sostenido por mucha deuda no es comparable a uno alcanzado con balance conservador.' },
            { q: '¿Para qué tipo de empresa es más útil el múltiplo P/S en lugar del P/E?', options: ['Empresas con Beneficio Neto muy estable y positivo', 'Empresas con Beneficio Neto negativo o muy volátil', 'Solo bancos y aseguradoras', 'Nunca es más útil que el P/E'], correct: 1, explanation: 'Cuando el Beneficio Neto es negativo o muy volátil, el P/E deja de ser útil — el P/S permite valorar en función de las ventas.' },
            { q: '¿Qué representa aproximadamente un PEG de 1?', options: ['La empresa no tiene crecimiento', 'Se está pagando un P/E aproximadamente igual a la tasa de crecimiento de beneficios esperada', 'Es siempre señal de sobrevaloración extrema', 'El PEG de 1 no tiene ninguna interpretación estándar'], correct: 1, explanation: 'Un PEG de 1 sugiere que el precio pagado está en línea con el crecimiento de beneficios esperado.' },
            { q: 'Solo los códigos de Formulario 4 de la SEC ___ y ___ son señales de convicción real de insiders.', options: ['A y M', 'P y S', 'F y G', 'C y A'], correct: 1, explanation: 'P (compra discrecional) y S (venta discrecional) son las únicas señales de convicción real; A, M, F, G, C son rutinarias.' },
            { q: '¿Por qué el % institucional se compara contra un precio de referencia de cierre trimestral en vez de un precio individual por institución?', options: ['Porque todos los 13F reportan al mismo cierre de trimestre — es una limitación estructural del propio formulario', 'Porque las instituciones lo solicitan así', 'Es un error de diseño de la terminal', 'No existe tal comparación en Research'], correct: 0, explanation: 'Es la limitación estructural de los 13F: todos reportan al mismo cierre trimestral.' },
        ]
    },

    22: {
        title: 'Quiz — El Triángulo RSU',
        questions: [
            { q: '¿Cuáles son los tres pilares del Triángulo RSU?', options: ['RSI, MACD y Bollinger', 'Order flow, posicionamiento y técnica', 'Ingresos, márgenes y beneficio', 'Mercado, sector y activo'], correct: 1, explanation: 'El Triángulo RSU combina tres fuentes independientes: flujo de opciones (Options Flow), posicionamiento (institucionales/insiders/corto interés) y técnica.' },
            { q: '¿Por qué importa que los tres pilares vengan de fuentes independientes entre sí?', options: ['No importa, es un detalle sin relevancia', 'Porque si tres fuentes no relacionadas coinciden, la probabilidad de que sea ruido baja considerablemente', 'Porque así se calculan más rápido', 'Porque una fuente sustituye a las otras dos'], correct: 1, explanation: 'La independencia es lo que da valor a la confluencia: si derivaran unas de otras, coincidir no aportaría información nueva.' },
            { q: 'Según la escala de confianza del Triángulo, ¿qué acción corresponde a 2 de 3 señales alineadas?', options: ['Tamaño completo, sin dudarlo', 'No operar en ningún caso', 'Tamaño reducido y stop ajustado', 'Ignorar la técnica por completo'], correct: 2, explanation: 'Con 2 de 3 señales hay sesgo razonable pero falta confirmación — se opera con tamaño reducido, no con tamaño completo.' },
            { q: 'En Options Flow, ¿qué indica específicamente un ratio Vol/OI alto en una operación?', options: ['Que la operación es simplemente un roll de una posición ya existente', 'Que se está abriendo una posición nueva, no ajustando una previa', 'Que el ticker no tiene liquidez', 'No tiene ninguna utilidad práctica'], correct: 1, explanation: 'Un Vol/OI alto respecto al interés abierto previo indica que el volumen del día corresponde mayormente a posición nueva.' },
            { q: '¿Qué hace más fiable al order flow alcista según la lección de Order Flow?', options: ['Que sea una única operación aislada, cuanto más grande mejor', 'Que se repita en la misma dirección durante varios días seguidos', 'Que se ejecute siempre como bloque y nunca como sweep', 'La fiabilidad no depende de la repetición'], correct: 1, explanation: 'La repetición durante varios días en la misma dirección descarta la casualidad y es más fiable que una operación aislada.' },
            { q: 'Para el pilar de posicionamiento, ¿qué combinación se describe como la lectura más sólida?', options: ['Solo corto interés elevado, sin ningún otro dato', 'Insiders comprando + % institucional al alza', 'Institucional a la baja sin actividad de insiders', 'Cualquier dato aislado sirve igual'], correct: 1, explanation: 'La combinación de compras insider recientes junto con titularidad institucional estable o creciente da la lectura de posicionamiento más sólida.' },
            { q: 'Según el checklist de confluencia, ¿cuál es el punto de partida recomendado para buscar setups del Triángulo?', options: ['Revisar la técnica de todos los tickers del mercado uno a uno', 'Escanear Options Flow, porque el order flow notable es la señal más escasa', 'Empezar siempre por el corto interés', 'No hay un orden recomendado'], correct: 1, explanation: 'El order flow notable es el pilar más escaso, por lo que escanearlo primero permite crear una lista corta de candidatos antes de revisar técnica y posicionamiento.' },
        ]
    },

    23: {
        title: 'Quiz — Convicción a Largo Plazo',
        questions: [
            { q: 'Según el módulo, ¿qué distingue a una empresa "cara pero con moat real" de una "burbuja narrativa"?', options: ['Nada, ambas son igual de arriesgadas', 'La existencia de barreras de entrada verificables (contratos, cuota de mercado, regulación), no solo el relato', 'El sector en el que operan', 'El tamaño de la empresa'], correct: 1, explanation: 'El filtro clave es la evidencia verificable del moat, no lo convincente que suene la narrativa.' },
            { q: '¿Qué debería hacer el inversor antes de aceptar una prima de valoración según la Lección 1?', options: ['Confiar en que "todo el mundo habla de la empresa"', 'Exigir evidencia concreta del moat: contratos, cuota de mercado, barreras regulatorias reales', 'Comprar directamente si el crecimiento parece alto', 'Ignorar la valoración por completo'], correct: 1, explanation: 'El módulo insiste en que el sentimiento de mercado no sustituye a la evidencia estructural verificable.' },
            { q: '¿Qué es una posición "misión crítica" tal y como se define en el módulo?', options: ['Cualquier empresa grande de un sector de moda', 'Una empresa que es una de las pocas capaces de resolver un cuello de botella concreto dentro de un tema secular', 'Una empresa con muchos analistas cubriéndola', 'Una empresa con alto volumen diario'], correct: 1, explanation: 'La clave no es pertenecer a un sector en crecimiento, sino ser indispensable dentro de él.' },
            { q: 'Antes de aceptar la tesis temática de una posición "misión crítica", ¿qué recomienda el módulo revisar adicionalmente?', options: ['Nada más, el checklist temático ya es suficiente', 'La ejecución financiera real de la empresa (márgenes, caja, balance) con las herramientas del Módulo 21', 'Solo el precio objetivo de un analista', 'El número de menciones en redes sociales'], correct: 1, explanation: 'La convicción temática sin ejecución financiera sólida es una apuesta narrativa, no una tesis completa.' },
            { q: 'Para una posición de convicción a largo plazo, ¿qué marco temporal debería guiar la evaluación de la tesis según el módulo?', options: ['El gráfico de 1 minuto', 'El gráfico diario exclusivamente', 'El gráfico semanal o mensual, dejando el diario para decisiones tácticas', 'No hace falta mirar ningún gráfico'], correct: 2, explanation: 'El semanal/mensual manda para la tesis de fondo; el diario queda como herramienta táctica para afinar entradas.' },
            { q: '¿Qué advierte el módulo sobre "la recuperación tras una corrección suele ser rápida"?', options: ['Que es una garantía absoluta, siempre se cumple', 'Que confundir una caída de ruido con una tesis rota es uno de los errores más caros de este estilo de inversión', 'Que nunca hay que revisar la tesis tras una caída', 'Que solo aplica a empresas pequeñas'], correct: 1, explanation: 'El módulo distingue explícitamente entre volatilidad normal y una corrección que refleja una tesis realmente rota.' },
            { q: 'Según la última lección, ¿cómo se traslada el control de riesgo en una posición de convicción que no usa un stop técnico ajustado?', options: ['No hay ningún control de riesgo posible en este estilo', 'Al tamaño de la posición dentro de la cartera total', 'Se controla solo con el precio objetivo', 'Se delega por completo en la opinión de otros inversores'], correct: 1, explanation: 'Cuando no se usa un stop ajustado porque se tolera más volatilidad, el tamaño de la posición pasa a ser la principal herramienta de control de riesgo.' },
        ]
    },

    24: {
        title: 'Quiz — Volatilidad, el VIX y la Oportunidad',
        questions: [
            { q: 'Según el módulo, ¿qué diferencia hay entre "volatilidad" y "pérdida permanente de capital"?', options: ['Son exactamente lo mismo', 'La volatilidad es el camino (dispersión de rendimientos); la pérdida permanente es el destino final — una cartera puede ser volátil y aun así terminar ganando', 'La volatilidad solo existe en criptomonedas', 'Una cartera volátil siempre pierde dinero a largo plazo'], correct: 1, explanation: 'El módulo distingue explícitamente el "camino" (volatilidad) del "destino" (resultado final) — pueden ser independientes.' },
            { q: '¿Qué mide realmente el VIX?', options: ['La dirección exacta que tomará el mercado', 'La magnitud de movimiento que el mercado espera en los próximos 30 días, sin decir si será al alza o a la baja', 'El precio objetivo del S&P 500', 'El volumen negociado en el S&P 500'], correct: 1, explanation: 'El VIX es volatilidad implícita a 30 días — magnitud esperada, no dirección.' },
            { q: 'Un VIX de 40, según lo explicado, ¿con qué escenarios es compatible?', options: ['Solo con una caída fuerte', 'Solo con una subida fuerte', 'Tanto con una caída fuerte como con una subida fuerte — el VIX no distingue entre las dos', 'Con que el mercado se mantenga plano'], correct: 2, explanation: 'Es precisamente el punto clave de la lección: el VIX alto es compatible con movimientos grandes en cualquier dirección.' },
            { q: '¿Qué widget de RSU Terminal se menciona como forma de ver si el mercado está en "contango" o "backwardation"?', options: ['Insider Flow', 'VIX Term Structure', 'Options Flow', 'Scanner'], correct: 1, explanation: 'El VIX Term Structure, ya construido en Market, muestra esta estructura y su propio tooltip explica que la backwardation señala capitulación.' },
            { q: '¿Por qué el módulo pide tratar con especial cautela la estadística de "picos de VIX seguidos de retornos positivos"?', options: ['Porque no ha pasado nunca en la historia del mercado', 'Porque la muestra de episodios extremos es pequeña, hay sesgo de superviviente, y "positivo a 3-6 meses" no significa "suelo inmediato"', 'Porque el VIX ya no se calcula igual que antes', 'Porque solo aplica fuera de Estados Unidos'], correct: 1, explanation: 'El módulo enumera varias razones de cautela estadística: muestra pequeña, sesgo de superviviente, y el riesgo de que el precio siga cayendo antes de girar.' },
            { q: 'Según el módulo, ¿qué debería hacer sospechar sobre una tabla de rendimientos de una gestora o fondo?', options: ['Que esté en una presentación bien diseñada', 'Que incluya avisos como "resultados hipotéticos" o "preparados con la ventaja de la retrospectiva" en la letra pequeña', 'Que use gráficos de colores', 'Que mencione el nombre del gestor'], correct: 1, explanation: 'Esos avisos son literalmente la propia gestora admitiendo que los números no son un histórico real y auditado.' },
            { q: 'Si se decide actuar sobre la tesis de "miedo extremo como oportunidad", ¿qué recomienda el módulo en lugar de un stop técnico muy ajustado?', options: ['No aplicar ningún control de riesgo', 'Trasladar el control de riesgo al tamaño de la posición y a una entrada escalonada, no a un stop que saltaría por el ruido normal', 'Invertir toda la cartera de una sola vez', 'Esperar a que el VIX vuelva a su media antes de hacer nada'], correct: 1, explanation: 'Mismo principio que el Módulo 23: cuando no se usa un stop ajustado, el tamaño de la posición pasa a ser la herramienta principal de control de riesgo.' },
        ]
    },

    25: {
        title: 'Quiz — Construir una Posición con DCA',
        questions: [
            { q: '¿Cómo define el módulo el DCA clásico?', options: ['Comprar más cuando el precio cae por debajo de un nivel definido', 'Invertir una cantidad fija a intervalos fijos de calendario, sin importar el precio', 'Invertir todo el capital disponible en un solo día', 'Vender parte de la posición cada mes'], correct: 1, explanation: 'DCA clásico está dirigido por el calendario (fecha fija), no por el nivel de precio.' },
            { q: 'Según la evidencia histórica citada en el módulo, ¿con qué frecuencia ha superado invertir de golpe al DCA en mercados con tendencia alcista de largo plazo?', options: ['Nunca', 'Aproximadamente 2 de cada 3 periodos analizados', 'Siempre, sin excepción', 'Solo en mercados bajistas'], correct: 1, explanation: 'Más tiempo invertido suele significar más tiempo componiendo — por eso invertir de golpe gana de media, aunque no siempre.' },
            { q: '¿Por qué elige mucha gente el DCA aunque no sea lo matemáticamente óptimo de media?', options: ['Porque no saben que invertir de golpe suele ganar más', 'Porque reduce el riesgo de cola (entrar de golpe justo antes de una caída fuerte) y es más fácil de sostener psicológicamente', 'Porque siempre genera más rentabilidad', 'Porque es obligatorio por ley'], correct: 1, explanation: 'El valor del DCA es la gestión del riesgo de cola y la disciplina psicológica, no una ventaja matemática garantizada.' },
            { q: '¿En qué se diferencia la "entrada escalonada" del DCA clásico?', options: ['En nada, son el mismo concepto con distinto nombre', 'La entrada escalonada está dirigida por el NIVEL DE PRECIO (comprar más cuanto más cae), no por el calendario', 'La entrada escalonada solo se puede hacer una vez al año', 'La entrada escalonada nunca se usa con instrumentos apalancados'], correct: 1, explanation: 'DCA = disciplina de calendario. Entrada escalonada = disciplina de nivel de precio. Son técnicas relacionadas pero distintas.' },
            { q: 'En el ejemplo del módulo, el S&P cae -10% y luego sube +11,1%, volviendo a su punto de partida (breakeven). ¿Qué le pasa a SPXL (3x) en el mismo escenario?', options: ['También vuelve exactamente al punto de partida', 'Cae -30% y sube +33,3%, pero se queda en torno a un -6% por debajo del punto de partida, por la decay diaria', 'Sube mucho más que el triple', 'No se ve afectado porque es un ETF'], correct: 1, explanation: 'El apalancamiento diario de SPXL hace que -30%/+33,3% NO sea breakeven — es el efecto de la volatility decay explicado en el módulo.' },
            { q: '¿Por qué la estrategia de SPXL en la propia terminal escala la posición por nivel de caída y no por calendario fijo?', options: ['Por casualidad, no hay una razón concreta', 'Porque comprar la misma cantidad cada mes en SPXL ignoraría la decay acumulada, mientras que escalar en la caída aprovecha el pánico y deja que la decay trabaje a favor en la recuperación', 'Porque el calendario fijo no está permitido para ETFs apalancados', 'Porque SPXL no tiene suficiente liquidez para DCA calendario'], correct: 1, explanation: 'En un instrumento con decay por apalancamiento, el nivel de caída es la información relevante, no la fecha del calendario.' },
            { q: 'Según la última lección, ¿qué debe definirse ANTES de empezar a construir una posición, ya sea con DCA calendario o entrada escalonada?', options: ['Nada, se puede decidir sobre la marcha', 'El tamaño máximo total de la posición dentro de la cartera', 'El precio exacto al que se venderá', 'El nombre que se le pondrá a la posición'], correct: 1, explanation: 'Ninguna de las dos técnicas de entrada sustituye a la gestión del riesgo — definen el CÓMO, no el CUÁNTO puede llegar a pesar la posición.' },
        ]
    },

    26: {
        title: 'Quiz — RSU Algoritmo',
        questions: [
            { q: '¿A qué pregunta responde el semáforo del RSU Algoritmo?', options: ['Qué valor concreto comprar hoy', 'Cuándo EMPEZAR a construir una posición en el mercado americano', 'Cuándo vender una posición abierta', 'Qué precio objetivo tiene el índice'], correct: 1, explanation: 'El semáforo responde CUÁNDO, no en qué ni cuándo salir. Marca el principio de un proceso de compra por tramos.' },
            { q: '¿Cuál de estos factores NO suma puntos a la nota de 0 a 100?', options: ['El miedo (VIX y su curva)', 'La vuelta a la media de 200 semanas', 'El FTD (día de seguimiento)', 'La capitulación por volumen'], correct: 2, explanation: 'El FTD no puntúa: ocurre DESPUÉS del suelo, no a la vez, así que se muestra como confirmación posterior y no como parte de la nota.' },
            { q: 'Además de superar el listón de la nota, ¿qué condición obligatoria hay que cumplir para que el semáforo se ponga verde?', options: ['Que el VIX supere 35', 'Que el precio haya vuelto a su media de 200 semanas (no más de un 10% por encima)', 'Que haya un FTD confirmado', 'Que el volumen doble su media'], correct: 1, explanation: 'Es la puerta: se puede tener mucho miedo y mucha sobreventa sin que el mercado se haya abaratado de verdad. La puerta separa un suelo de un susto.' },
            { q: '¿Por qué el listón para dar verde baja a 60 cuando el precio está por encima de su media de 200 días?', options: ['Por un sesgo optimista del sistema', 'Porque una caída dentro de una tendencia que sigue viva tiende a resolverse mejor que un rebote en un mercado ya roto', 'Porque en tendencia alcista hay menos datos disponibles', 'Porque el VIX pesa menos en tendencia alcista'], correct: 1, explanation: 'La exigencia SUBE a 70 en el escenario más peligroso, que es el mercado ya roto donde cada rebote parece un suelo y casi ninguno lo es.' },
            { q: 'El semáforo está en ÁMBAR. ¿Qué corresponde hacer?', options: ['Entrar con un primer tramo pequeño', 'Nada, volver cuando se ponga verde', 'Mirar la lista de candidatos y dejar decidido qué se compraría y con cuánto', 'Cerrar todas las posiciones abiertas'], correct: 2, explanation: 'El ámbar es la fase de preparación: es el último momento en que se puede decidir con calma. Si cuando llega el verde hay que empezar a decidir, se llega tarde.' },
            { q: 'Según el backtest, ¿qué ocurre con la señal a 5 y 10 días?', options: ['Es cuando más ventaja aporta', 'Va por detrás de comprar en cualquier otro día de pánico comparable', 'Da exactamente el mismo resultado que el índice', 'No hay datos para esos plazos'], correct: 1, explanation: 'A corto plazo la señal resta: se compra DURANTE la caída y la caída sigue unos días más. La ventaja aparece a partir del mes y sobre todo a 60 días.' },
            { q: '¿Por qué la estrategia del semáforo no lleva stop loss?', options: ['Por descuido en el diseño', 'Porque un stop del 7% habría cortado 5 de las 16 señales históricas, incluidas las dos de marzo de 2020, y la ventaja desaparecía entera', 'Porque los stops no existen en los brokers americanos', 'Porque el sistema nunca entra en pérdidas'], correct: 1, explanation: 'El sistema compra a propósito mientras el precio todavía cae; un stop cerrado vende exactamente en el momento para el que la señal fue diseñada. El control del riesgo pasa a ser el tamaño de la posición.' },
            { q: 'Históricamente, ¿cuánto llegaron a estar en rojo estas señales antes de funcionar?', options: ['Nunca entraron en pérdidas', 'Un 6% de media y un 20% en el peor caso (marzo de 2020)', 'Un 1% de media como máximo', 'Un 50% de media'], correct: 1, explanation: 'Ese número es la regla práctica del tamaño: si ver la posición un 20% abajo te llevaría a venderla, la posición es demasiado grande.' },
            { q: 'Los cinco candidatos que muestra el módulo se eligen por ser los más FUERTES del índice, no los más castigados. ¿Por qué?', options: ['Porque son más baratos', 'Porque después de un suelo lo que suele recuperar antes y mejor es lo que menos cayó', 'Porque tienen más volumen', 'Porque es más fácil de calcular'], correct: 1, explanation: 'Lo que más ha caído suele haberlo hecho por una razón concreta, y a menudo tarda años en volver — o no vuelve. Es la misma lógica de Weinstein y del Módulo 3.' },
            { q: 'Las 16 señales históricas acabaron todas en positivo a 60 días. ¿Cómo debe interpretarse ese 100%?', options: ['Como una garantía de que la próxima señal también será positiva', 'Como un número que con solo 16 casos no se debe esperar que se repita', 'Como prueba de que el sistema no puede fallar', 'Como un error de cálculo'], correct: 1, explanation: 'Lo que sostiene al sistema no es ese 100%, sino que la ventaja aparece en dos periodos independientes y siempre en el mismo plazo. Los suelos son raros: 16 en 18 años es una muestra pequeña.' },
        ]
    },

    27: {
        title: 'Quiz — La Cartera RSU',
        questions: [
            { q: 'El reparto en cuatro bloques (Estrategia SPXL, RSU Stocks, Cryptos, Beta Stocks), ¿se ve entero en la página Cartera?', options: ['Sí, los cuatro bloques están en esa tabla', 'No: la Cartera muestra dos de ellos; SPXL y la parte de criptomonedas tienen su propio módulo', 'No, la Cartera no muestra ninguno de los cuatro', 'Solo se ve el bloque de Cryptos'], correct: 1, explanation: 'La Cartera cubre RSU Stocks y Beta Stocks. Buscar la estrategia SPXL dentro de la tabla de posiciones es buscar en el sitio equivocado: esa parte se gestiona por fases en el módulo SPXL.' },
            { q: 'El gráfico del reparto lleva la fecha de septiembre de 2025. ¿Qué representa?', options: ['Los pesos reales que tiene la cartera hoy mismo', 'El reparto OBJETIVO del diseño en esa fecha; los pesos reales de hoy los da la sección ASIGNACIÓN', 'Una simulación sin relación con la cartera real', 'El reparto que tendrá la cartera dentro de un año'], correct: 1, explanation: 'Es el objetivo, no una foto del presente. Los pesos reales se mueven solos porque el mercado mueve los precios, y por eso la terminal calcula el real aparte.' },
            { q: '¿Qué diferencia hay entre el bloque del reparto y el nivel CORE/HIGH/LOTTERY?', options: ['Son dos nombres para lo mismo', 'El bloque dice de qué familia de riesgo es la posición; el nivel dice cuánto capital le corresponde', 'El bloque lo decide la terminal y el nivel el usuario', 'El nivel solo se aplica a las criptomonedas'], correct: 1, explanation: 'Son dos preguntas independientes. Dentro del mismo bloque puede haber posiciones de nivel CORE y de nivel LOTTERY.' },
            { q: 'Según la tesis del módulo, ¿qué se está comprando en una posición de la parte de acciones?', options: ['Un beneficio actual barato según el ratio precio/beneficio', 'Una posición dentro de una tendencia estructural de varios años, en compañías difíciles de sustituir dentro de ella', 'Un valor que acaba de romper máximos en el gráfico diario', 'La empresa con el dividendo más alto del sector'], correct: 1, explanation: 'Un ratio de valoración compara el precio de hoy con el beneficio de hoy: es una foto. La tesis se apoya en el sitio que ocupa la compañía dentro de una corriente de varios años.' },
            { q: '¿Qué significa que una compañía sea de misión crítica?', options: ['Que trabaja para el Gobierno', 'Que quitarla del proceso lo detiene, y sustituirla es caro, lento o imposible a corto plazo', 'Que su acción es muy volátil', 'Que tiene el mayor beneficio de su sector'], correct: 1, explanation: 'Esa dificultad de sustitución es lo que sostiene los márgenes durante años, y es justo lo que un ratio de valoración de un solo ejercicio no recoge.' },
            { q: 'Las posiciones con prima de valoración caen más fuerte en las correcciones. ¿Cómo se interpreta eso en este módulo?', options: ['Como un fallo de la selección que hay que corregir vendiendo', 'Como el precio que se paga por estar en el sitio correcto — pero solo mientras la tesis siga intacta', 'Como una garantía de que después recuperarán con fuerza', 'Como una señal de que hay que aumentar la posición sin más'], correct: 1, explanation: 'La caída fuerte es segura; la recuperación no. Hay compañías con prima que caen y no vuelven porque la tesis estaba mal. Por eso la tesis se revisa, no solo se aguanta.' },
            { q: '¿Cuál es la pregunta que separa una caída que es ruido de una que es información?', options: ['¿Ha caído más de un 20%?', 'Si hoy no tuvieras la posición y leyeras la tesis por primera vez, ¿la comprarías al precio de hoy?', '¿Está por debajo de su media de 200 días?', '¿Han salido noticias en prensa esta semana?'], correct: 1, explanation: 'Si la respuesta es sí, ha caído el precio pero la tesis sigue en pie. Si es no, lo que ha cambiado es la razón por la que la posición estaba ahí.' },
            { q: 'Los niveles asignan 5%, 3% y 1% del capital base. ¿Por qué se decide el tamaño ANTES de comprar?', options: ['Porque el bróker lo exige', 'Porque decidirlo al comprar es decidirlo con entusiasmo y sin haber vivido todavía la primera caída del 30%', 'Porque así se paga menos comisión', 'Porque el precio de entrada no se conoce hasta después'], correct: 1, explanation: 'Con niveles fijos la pregunta deja de ser «cuánto meto en esto» (emocional) y pasa a ser «¿esto es CORE, HIGH o LOTTERY?» (sobre la calidad de la tesis). El tamaño sale solo.' },
            { q: 'Una posición aparece marcada como SIN ASIGNAR en la tabla. ¿Qué significa?', options: ['Que la posición vale cero', 'Que las reglas de nivel se quedaron sin capital antes de llegar a ella, así que todavía no tiene tamaño asignado', 'Que la posición está cerrada', 'Que falta el precio de mercado de ese valor'], correct: 1, explanation: 'Un 0% a secas se leería como «esto no pesa nada», que es distinto. Se corrige cerrando posiciones, bajando los pesos por nivel o subiendo el capital base — nunca inventando capital que no existe.' },
            { q: '¿Por qué la curva de patrimonio usa el retorno ponderado por tiempo en vez de comparar el valor final con el inicial?', options: ['Porque es más fácil de calcular', 'Porque en una cartera que se está construyendo la resta simple mide sobre todo el dinero nuevo aportado, no la rentabilidad', 'Porque el valor inicial no se conoce', 'Porque así el resultado siempre sale positivo'], correct: 1, explanation: 'Una cartera que pasa de 10.000 a 30.000 tras aportar 18.000 no ha ganado un 200%. El retorno ponderado por tiempo descuenta cada aportación del día en que entró antes de medir.' },
        ]
    },

};