// ─────────────────────────────────────────────────────────────────────────────
// RSU ACADEMY — Manifiesto de lecciones (GENERADO, no editar a mano)
//
// Índice ligero de academy_lessons.js: qué lecciones existen, su título y su
// extensión. Se importa de forma ESTÁTICA en academy.js para poder pintar el
// índice de módulos, el tiempo de lectura y la barra de progreso sin cargar
// los ~525 KB de contenido ni los ~684 KB de gráficos.
//
// Regenerar tras añadir o editar lecciones:  python scripts/gen_academy_manifest.py
// ─────────────────────────────────────────────────────────────────────────────

export const PALABRAS_POR_MINUTO = 200;

export const LESSON_INDEX = {
    '0-1': { title: 'Qué es RSU Terminal', words: 447 },
    '0-2': { title: 'La Metodología RSU', words: 539 },
    '0-3': { title: 'Las Herramientas', words: 417 },
    '0-4': { title: 'Flujo de Trabajo Semanal', words: 453 },
    '1-1': { title: 'Gráfico Mensual — La visión macro', words: 447 },
    '1-2': { title: 'Gráfico Semanal — La tendencia media', words: 448 },
    '1-3': { title: 'Gráfico Diario — El setup operativo', words: 414 },
    '1-4': { title: 'Velas Limpias — Sin ruido visual', words: 500 },
    '1-5': { title: 'Medias Móviles Exponenciales (EMA)', words: 1238 },
    '2-1': { title: 'Máximos Crecientes — Señal alcista', words: 457 },
    '2-2': { title: 'Mínimos Crecientes — Soporte dinámico', words: 565 },
    '2-3': { title: 'Máximos Decrecientes — Señal bajista', words: 569 },
    '2-4': { title: 'Mínimos Decrecientes — Presión vendedora', words: 662 },
    '3-1': { title: 'Tendencia Alcista — Cómo montarla', words: 604 },
    '3-2': { title: 'Tendencia Bajista — Cómo evitarla', words: 593 },
    '3-3': { title: 'Rango Lateral — Paciencia obligatoria', words: 601 },
    '3-4': { title: 'Validación de Líneas de Tendencia', words: 634 },
    '4-1': { title: 'Soporte Fresco — Primera vez testeado', words: 577 },
    '4-2': { title: 'Resistencia Mayor — Donde venden los grandes', words: 575 },
    '4-3': { title: 'Marcado de Zonas — Técnica profesional', words: 602 },
    '4-4': { title: 'Niveles con Múltiples Toques', words: 643 },
    '5-1': { title: 'Zonas de Demanda', words: 638 },
    '5-2': { title: 'Zonas de Oferta', words: 576 },
    '5-3': { title: 'Áreas de Rechazo', words: 615 },
    '5-4': { title: 'Formación de Base', words: 662 },
    '6-1': { title: 'Engulfing Alcista', words: 550 },
    '6-2': { title: 'Engulfing Bajista', words: 526 },
    '6-3': { title: 'Pin Bar', words: 588 },
    '6-4': { title: 'Inside Bar', words: 604 },
    '7-1': { title: 'Ruptura de Rango', words: 609 },
    '7-2': { title: 'Ruptura de Tendencia', words: 514 },
    '7-3': { title: 'Ruptura de Soporte', words: 623 },
    '7-4': { title: 'Entradas en Retest', words: 670 },
    '8-1': { title: 'Volumen en Rupturas', words: 529 },
    '8-2': { title: 'Bajo Volumen en Retrocesos', words: 494 },
    '8-3': { title: 'Volumen Clímax', words: 1297 },
    '8-4': { title: 'Participación Débil', words: 549 },
    '9-1': { title: 'Triángulo Ascendente', words: 539 },
    '9-2': { title: 'Triángulo Descendente', words: 492 },
    '9-3': { title: 'Rectángulo', words: 514 },
    '9-4': { title: 'Bandera y Asta', words: 568 },
    '10-1': { title: 'Sesgo Mensual', words: 564 },
    '10-2': { title: 'Estructura Semanal', words: 537 },
    '10-3': { title: 'Setup Diario', words: 568 },
    '10-4': { title: 'Trigger en TF Menor', words: 632 },
    '10-5': { title: 'Configurar tu Watchlist', words: 837 },
    '11-1': { title: 'Definir el Setup', words: 525 },
    '11-2': { title: 'Ratio Riesgo/Recompensa', words: 559 },
    '11-3': { title: 'Tamaño de Posición', words: 535 },
    '11-4': { title: 'El Plan de Trade', words: 511 },
    '12-1': { title: 'Riesgo Fijo por Trade', words: 592 },
    '12-2': { title: 'Stop Loss Dinámico', words: 557 },
    '12-3': { title: 'Revenge Trading y Racha Perdedora', words: 533 },
    '12-4': { title: 'Protección de Capital', words: 420 },
    '13-1': { title: 'Esperar Confirmación', words: 445 },
    '13-2': { title: 'Evitar Entradas Prematuras', words: 462 },
    '13-3': { title: 'Seguir el Plan', words: 549 },
    '13-4': { title: 'Salir Sin Ego', words: 478 },
    '14-1': { title: 'Falsas Rupturas', words: 454 },
    '14-2': { title: 'Entradas Tardías', words: 478 },
    '14-3': { title: 'Sobretrading', words: 423 },
    '14-4': { title: 'Ignorar el Volumen', words: 445 },
    '15-1': { title: 'Captura de Pantalla', words: 430 },
    '15-2': { title: 'Registro de Errores', words: 456 },
    '15-3': { title: 'Revisión del Setup', words: 426 },
    '15-4': { title: 'Lecciones Aprendidas', words: 482 },
    '16-1': { title: 'Etapa 1 — Acumulación', words: 624 },
    '16-2': { title: 'Etapa 2 — Avance', words: 511 },
    '16-3': { title: 'Etapa 3 — Distribución', words: 559 },
    '16-4': { title: 'Etapa 4 — Declive', words: 588 },
    '17-1': { title: 'La Máquina de Descontar', words: 565 },
    '17-2': { title: 'Buy the Rumour', words: 528 },
    '17-3': { title: 'Sell the News', words: 554 },
    '17-4': { title: 'Earnings y Eventos Macro', words: 590 },
    '18-1': { title: 'La Zona de Entrada lo Decide Todo', words: 662 },
    '18-2': { title: 'Anatomía de una Buena Zona de Demanda', words: 618 },
    '18-3': { title: 'El Lado Psicológico del Buen R:R', words: 596 },
    '18-4': { title: 'Aplicar el R:R desde la Zona, no desde la Calculadora', words: 625 },
    '19-1': { title: 'Reversión y Ruptura de Línea de Tendencia', words: 444 },
    '19-2': { title: 'Soporte y Resistencia como Confirmación', words: 438 },
    '19-3': { title: 'Retroceso de Fibonacci', words: 402 },
    '19-4': { title: 'Consolidaciones', words: 396 },
    '19-5': { title: 'Gaps de Precio', words: 479 },
    '19-6': { title: 'Volumen Clímax y Tendencia', words: 417 },
    '20-1': { title: 'Qué Mide el RSU Score', words: 462 },
    '20-2': { title: 'Piotroski F-Score — Salud Financiera', words: 489 },
    '20-3': { title: 'Comparativa Sectorial — Valorar en Contexto', words: 444 },
    '20-4': { title: 'Cómo Leer Todo Junto', words: 404 },
    '21-1': { title: 'Ingresos, Márgenes y Beneficio', words: 364 },
    '21-2': { title: 'Rentabilidad y Eficiencia — ROE, ROA', words: 446 },
    '21-3': { title: 'Valoración — P/E, PEG, EV/EBITDA, P/S, P/B', words: 430 },
    '21-4': { title: 'Catalizadores — Earnings, Insiders, Institucionales', words: 459 },
    '22-1': { title: 'Los Tres Pilares del Triángulo', words: 559 },
    '22-2': { title: 'Order Flow — La Huella del Dinero Grande', words: 471 },
    '22-3': { title: 'Posicionamiento — Qué Apuesta el Mercado', words: 443 },
    '22-4': { title: 'El Checklist de Confluencia', words: 496 },
    '23-1': { title: 'Pagar la Prima por Posición Estratégica', words: 428 },
    '23-2': { title: 'Identificar Posiciones "Misión Crítica"', words: 422 },
    '23-3': { title: 'El Marco Temporal de la Convicción', words: 332 },
    '23-4': { title: 'Convicción Propia y Gestión del Riesgo', words: 400 },
    '24-1': { title: 'Volatilidad: Dispersión, no Pérdida', words: 320 },
    '24-2': { title: 'El VIX — Qué Mide y Qué NO Mide', words: 346 },
    '24-3': { title: 'Picos de Miedo y Reversión a la Media', words: 512 },
    '24-4': { title: 'Usarlo con Criterio, no a Ciegas', words: 323 },
    '25-1': { title: 'DCA Clásico — Mecánica y Psicología', words: 261 },
    '25-2': { title: 'DCA vs. Invertir de Golpe — la Evidencia', words: 353 },
    '25-3': { title: 'DCA vs. Entrada Escalonada — No son lo Mismo', words: 466 },
    '25-4': { title: 'Construir tu Propia Posición con Criterio', words: 343 },
    '26-1': { title: 'Qué es el Semáforo y Por Qué Existe', words: 582 },
    '26-2': { title: 'Cómo se Forma la Nota — Los Cinco Factores', words: 709 },
    '26-3': { title: 'La Puerta y el Listón', words: 586 },
    '26-4': { title: 'Los Cinco Colores y Cuándo Cambian', words: 420 },
    '26-5': { title: 'Cómo se Usa, Paso a Paso', words: 544 },
    '26-6': { title: 'Qué ha Hecho Históricamente', words: 747 },
    '26-7': { title: 'Cuánto Duele por el Camino, y Por Qué No Hay Stop', words: 506 },
    '26-8': { title: 'Límites y Glosario', words: 635 },
    '27-1': { title: 'Qué es la Cartera RSU', words: 463 },
    '27-2': { title: 'La Tesis de Fondo — Por Qué Estas Empresas', words: 738 },
    '27-3': { title: 'La Prima de Valoración y la Volatilidad', words: 579 },
    '27-4': { title: 'El Horizonte — Semanal y Mensual, No Diario', words: 488 },
    '27-5': { title: 'Los Niveles — CORE, HIGH y LOTTERY', words: 670 },
    '27-6': { title: 'Leer la Pantalla — Las Tarjetas de Cabecera', words: 577 },
    '27-7': { title: 'La Tabla, el Riesgo y la Asignación', words: 675 },
    '27-8': { title: 'Evolución, Cerradas, Límites y Glosario', words: 962 },
    '28-1': { title: 'Qué es CANSLIM y Para Qué Sirve', words: 428 },
    '28-2': { title: 'Las Siete Letras, Una a Una', words: 585 },
    '28-3': { title: 'Cómo Leer la Tabla del Buscador', words: 543 },
    '28-4': { title: 'El Análisis Individual', words: 454 },
    '28-5': { title: 'Cómo Usarlo Sin Hacerse Daño', words: 683 },
    '29-1': { title: 'Qué es la Fuerza Relativa', words: 506 },
    '29-2': { title: 'El Percentil — Qué Significa Ese Número', words: 445 },
    '29-3': { title: 'Cómo Leer la Pantalla', words: 474 },
    '29-4': { title: 'De la Foto a la Película', words: 593 },
    '29-5': { title: 'Tu Cartera y Cómo Usarlo Sin Hacerse Daño', words: 486 },
};
